In [17]:
import pandas as pd

In [18]:
# read and show the dataset
df_crop = pd.read_csv("soil_geotech_data.csv")
df_crop

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,29.96,55.46,24.12,Loamy,Cotton,8,19,16,Urea
1,36.83,69.28,25.17,Red,Wheat,17,0,28,28-28
2,26.95,60.64,35.66,Red,Barley,35,4,3,Urea
3,31.23,44.60,25.08,Red,Maize,17,3,12,DAP
4,33.78,51.39,47.60,Black,Cotton,9,9,34,28-28
...,...,...,...,...,...,...,...,...,...
331,35.30,59.61,44.25,Loamy,Oil seeds,10,14,10,Urea
332,39.39,71.67,49.34,Black,Barley,35,0,0,10-26-26
333,35.79,67.64,45.04,Red,Barley,41,0,0,Urea
334,37.78,73.38,36.03,Black,Tobacco,10,3,30,DAP
335,31.38,48.73,62.27,Loamy,Millets,11,2,33,28-28

In [19]:
df_crop['Temp_round'] = df_crop['Temparature'].round(0)
df_crop['Moist_round'] = df_crop['Moisture'].round(0)

df_crop.pivot_table(index='Temp_round', columns='Moist_round', values='Humidity', aggfunc='mean')

Moist_round,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0,...,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0,69.0,70.0
Temp_round,,,,,,,,,,,,,,,,,,,,,
21.0,NaN,NaN,NaN,NaN,48.700,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,58.50,NaN,NaN,NaN,NaN
22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23.0,NaN,NaN,NaN,NaN,NaN,NaN,53.88,47.76,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.67,NaN,NaN
24.0,48.68,NaN,NaN,NaN,58.360,NaN,NaN,49.03,NaN,NaN,...,NaN,NaN,NaN,59.99,NaN,NaN,NaN,NaN,NaN,57.64
25.0,NaN,NaN,NaN,55.05,NaN,NaN,NaN,NaN,47.40,45.345,...,NaN,NaN,NaN,NaN,52.43,NaN,NaN,NaN,NaN,NaN
26.0,57.90,68.60,NaN,NaN,NaN,57.930,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,51.73,NaN,NaN,NaN,NaN,NaN,60.39
27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.02,NaN,NaN,...,NaN,NaN,NaN,46.67,NaN,NaN,NaN,NaN,59.32,NaN
28.0,NaN,NaN,NaN,NaN,65.370,66.440,NaN,NaN,49.45,51.970,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29.0,63.97,64.47,55.023333,NaN,NaN,NaN,NaN,NaN,55.00,NaN,...,NaN,59.78,NaN,NaN,NaN,NaN,65.730,NaN,NaN,56.08
30.0,NaN,43.20,NaN,NaN,55.460,NaN,66.48,NaN,53.75,71.930,...,NaN,NaN,NaN,NaN,65.10,NaN,NaN,NaN,58.63,NaN
31.0,60.38,NaN,NaN,NaN,NaN,51.055,NaN,58.28,NaN,NaN,...,NaN,48.73,NaN,NaN,NaN,NaN,NaN,66.10,NaN,NaN
32.0,NaN,NaN,NaN,NaN,64.125,NaN,58.76,NaN,NaN,NaN,...,NaN,63.87,48.95,NaN,NaN,NaN,58.520,NaN,NaN,NaN
33.0,NaN,NaN,NaN,NaN,59.630,57.340,57.91,NaN,66.86,NaN,...,73.20,NaN,NaN,NaN,NaN,67.38,61.075,NaN,NaN,NaN
34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.96,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35.0,NaN,NaN,NaN,NaN,NaN,NaN,68.96,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71.27
36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.06,NaN,61.770,...,NaN,59.14,NaN,66.52,71.00,NaN,NaN,NaN,NaN,NaN
37.0,NaN,NaN,NaN,57.38,NaN,69.280,NaN,62.34,NaN,NaN,...,66.29,NaN,56.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38.0,NaN,NaN,NaN,NaN,66.520,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.96
39.0,NaN,NaN,NaN,NaN,NaN,NaN,64.33,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40.0,NaN,NaN,NaN,NaN,NaN,NaN,63.60,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 1. pivot()

In [20]:
# reshape the dataframe with .pivot()
df_crop.pivot(index="Temparature", columns="Moisture", values="Humidity")

Moisture,20.00,20.69,20.75,21.33,21.39,22.32,22.33,22.41,22.56,22.77,...,66.67,66.90,67.41,67.51,68.46,68.75,68.93,69.57,69.64,70.00
Temparature,,,,,,,,,,,,,,,,,,,,,
20.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20.85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21.42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39.39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39.81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
df_crop['Temp_round'] = df_crop['Temparature'].round(0)
df_crop['Moist_round'] = df_crop['Moisture'].round(0)

df_crop.pivot_table(index='Temp_round', columns='Moist_round', values='Humidity', aggfunc='mean')

Moist_round,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0,...,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0,69.0,70.0
Temp_round,,,,,,,,,,,,,,,,,,,,,
21.0,NaN,NaN,NaN,NaN,48.700,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,58.50,NaN,NaN,NaN,NaN
22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23.0,NaN,NaN,NaN,NaN,NaN,NaN,53.88,47.76,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.67,NaN,NaN
24.0,48.68,NaN,NaN,NaN,58.360,NaN,NaN,49.03,NaN,NaN,...,NaN,NaN,NaN,59.99,NaN,NaN,NaN,NaN,NaN,57.64
25.0,NaN,NaN,NaN,55.05,NaN,NaN,NaN,NaN,47.40,45.345,...,NaN,NaN,NaN,NaN,52.43,NaN,NaN,NaN,NaN,NaN
26.0,57.90,68.60,NaN,NaN,NaN,57.930,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,51.73,NaN,NaN,NaN,NaN,NaN,60.39
27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.02,NaN,NaN,...,NaN,NaN,NaN,46.67,NaN,NaN,NaN,NaN,59.32,NaN
28.0,NaN,NaN,NaN,NaN,65.370,66.440,NaN,NaN,49.45,51.970,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29.0,63.97,64.47,55.023333,NaN,NaN,NaN,NaN,NaN,55.00,NaN,...,NaN,59.78,NaN,NaN,NaN,NaN,65.730,NaN,NaN,56.08
30.0,NaN,43.20,NaN,NaN,55.460,NaN,66.48,NaN,53.75,71.930,...,NaN,NaN,NaN,NaN,65.10,NaN,NaN,NaN,58.63,NaN
31.0,60.38,NaN,NaN,NaN,NaN,51.055,NaN,58.28,NaN,NaN,...,NaN,48.73,NaN,NaN,NaN,NaN,NaN,66.10,NaN,NaN
32.0,NaN,NaN,NaN,NaN,64.125,NaN,58.76,NaN,NaN,NaN,...,NaN,63.87,48.95,NaN,NaN,NaN,58.520,NaN,NaN,NaN
33.0,NaN,NaN,NaN,NaN,59.630,57.340,57.91,NaN,66.86,NaN,...,73.20,NaN,NaN,NaN,NaN,67.38,61.075,NaN,NaN,NaN
34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.96,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35.0,NaN,NaN,NaN,NaN,NaN,NaN,68.96,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71.27
36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.06,NaN,61.770,...,NaN,59.14,NaN,66.52,71.00,NaN,NaN,NaN,NaN,NaN
37.0,NaN,NaN,NaN,57.38,NaN,69.280,NaN,62.34,NaN,NaN,...,66.29,NaN,56.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38.0,NaN,NaN,NaN,NaN,66.520,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.96
39.0,NaN,NaN,NaN,NaN,NaN,NaN,64.33,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40.0,NaN,NaN,NaN,NaN,NaN,NaN,63.60,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN