In [1]:
import pandas as pd

In [8]:
df_cpcb_dataset = pd.read_csv('concrete.csv')

In [9]:
df_cpcb_dataset.head(3)

,cement,slag,ash,water,superplastic,coarseagg,fineagg,age,strength
0,141.3,212.0,0.0,203.5,0.0,971.8,748.5,28,29.89
1,168.9,42.2,124.3,158.3,10.8,1080.8,796.2,14,23.51
2,250.0,0.0,95.7,187.4,5.5,956.9,861.2,28,29.22

# 1 Filter dataframe based on a condition

In [12]:
# find which rows have "200" in the "Cement" column
df_cpcb_dataset['cement']==250

0       False
1       False
2        True
3       False
4       False
        ...
1025    False
1026    False
1027    False
1028    False
1029    False
Name: cement, Length: 1030, dtype: bool

In [14]:
df_cpcb_dataset['cement']!=250

0        True
1        True
2       False
3        True
4        True
        ...
1025     True
1026     True
1027     True
1028     True
1029     True
Name: cement, Length: 1030, dtype: bool

In [16]:
# filter dataframe based on condition
df_cpcb_dataset[df_cpcb_dataset['cement']==250]

,cement,slag,ash,water,superplastic,coarseagg,fineagg,age,strength
2,250.0,0.0,95.7,187.4,5.5,956.9,861.2,28,29.22
59,250.0,0.0,95.7,187.4,5.5,956.9,861.2,100,42.35
121,250.0,0.0,95.7,191.8,5.3,948.9,857.2,56,39.64
358,250.0,0.0,95.7,187.4,5.5,956.9,861.2,14,24.92
422,250.0,0.0,95.7,187.4,5.5,956.9,861.2,3,13.82
618,250.0,0.0,95.7,187.4,5.5,956.9,861.2,56,38.33
650,250.0,0.0,95.7,191.8,5.3,948.9,857.2,3,8.49
659,250.0,0.0,0.0,182.0,0.0,1100.0,820.0,7,12.73
812,250.0,0.0,95.7,191.8,5.3,948.9,857.2,14,24.66
818,250.0,0.0,0.0,182.0,0.0,1100.0,820.0,28,20.87
824,250.0,180.0,95.0,159.0,9.5,860.0,800.0,28,67.87
893,250.0,0.0,95.7,191.8,5.3,948.9,857.2,100,41.16
1004,250.0,0.0,95.7,191.8,5.3,948.9,857.2,28,27.22

In [17]:
# verify which companies are in the "Company" olumn with value_counts()
df_cpcb_dataset[df_cpcb_dataset['cement']==250].value_counts('cement')

cement
250.0    13
Name: count, dtype: int64

# 1.1 Excercise 1

In [22]:
# find which rows don't have "250" in the "cement" column
df_cpcb_dataset['cement']!=250

0        True
1        True
2       False
3        True
4        True
        ...
1025     True
1026     True
1027     True
1028     True
1029     True
Name: cement, Length: 1030, dtype: bool

In [23]:
# filter dataframe based on a dataframe
df_cpcb_dataset[df_cpcb_dataset['cement']!=250]

,cement,slag,ash,water,superplastic,coarseagg,fineagg,age,strength
0,141.3,212.0,0.0,203.5,0.0,971.8,748.5,28,29.89
1,168.9,42.2,124.3,158.3,10.8,1080.8,796.2,14,23.51
3,266.0,114.0,0.0,228.0,0.0,932.0,670.0,28,45.85
4,154.8,183.4,0.0,193.3,9.1,1047.4,696.7,28,18.29
5,255.0,0.0,0.0,192.0,0.0,889.8,945.0,90,21.86
...,...,...,...,...,...,...,...,...,...
1025,135.0,0.0,166.0,180.0,10.0,961.0,805.0,28,13.29
1026,531.3,0.0,0.0,141.8,28.2,852.1,893.7,3,41.30
1027,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1028,342.0,38.0,0.0,228.0,0.0,932.0,670.0,270,55.06
1029,540.0,0.0,0.0,173.0,0.0,1125.0,613.0,7,52.61

# 1.2 Excercise 2

In [24]:
# find cement with price over 400
df_cpcb_dataset['cement']>400

0       False
1       False
2       False
3       False
4       False
        ...
1025    False
1026     True
1027    False
1028    False
1029     True
Name: cement, Length: 1030, dtype: bool