In [1]:
import pandas as pd

In [2]:
# read csv file
df = pd.read_csv('soil_geotech_data.csv')

In [3]:
# show dataframe
df

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,29.96,55.46,24.12,Loamy,Cotton,8,19,16,Urea
1,36.83,69.28,25.17,Red,Wheat,17,0,28,28-28
2,26.95,60.64,35.66,Red,Barley,35,4,3,Urea
3,31.23,44.60,25.08,Red,Maize,17,3,12,DAP
4,33.78,51.39,47.60,Black,Cotton,9,9,34,28-28
...,...,...,...,...,...,...,...,...,...
331,35.30,59.61,44.25,Loamy,Oil seeds,10,14,10,Urea
332,39.39,71.67,49.34,Black,Barley,35,0,0,10-26-26
333,35.79,67.64,45.04,Red,Barley,41,0,0,Urea
334,37.78,73.38,36.03,Black,Tobacco,10,3,30,DAP
335,31.38,48.73,62.27,Loamy,Millets,11,2,33,28-28

# 1. copy()
1.1 deep = True

In [4]:
# deeo=True by deault (Modifications to the data or indices of the copy )
df_copy = df.copy()

In [6]:
# update valuein original dataframe
df.loc[4,'Moisture'] = 40

In [7]:
# copy vs original dataframe
df

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,29.96,55.46,24.12,Loamy,Cotton,8,19,16,Urea
1,36.83,69.28,25.17,Red,Wheat,17,0,28,28-28
2,26.95,60.64,35.66,Red,Barley,35,4,3,Urea
3,31.23,44.60,25.08,Red,Maize,17,3,12,DAP
4,33.78,51.39,40.00,Black,Cotton,9,9,34,28-28
...,...,...,...,...,...,...,...,...,...
331,35.30,59.61,44.25,Loamy,Oil seeds,10,14,10,Urea
332,39.39,71.67,49.34,Black,Barley,35,0,0,10-26-26
333,35.79,67.64,45.04,Red,Barley,41,0,0,Urea
334,37.78,73.38,36.03,Black,Tobacco,10,3,30,DAP
335,31.38,48.73,62.27,Loamy,Millets,11,2,33,28-28

In [8]:
df_copy

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,29.96,55.46,24.12,Loamy,Cotton,8,19,16,Urea
1,36.83,69.28,25.17,Red,Wheat,17,0,28,28-28
2,26.95,60.64,35.66,Red,Barley,35,4,3,Urea
3,31.23,44.60,25.08,Red,Maize,17,3,12,DAP
4,33.78,51.39,47.60,Black,Cotton,9,9,34,28-28
...,...,...,...,...,...,...,...,...,...
331,35.30,59.61,44.25,Loamy,Oil seeds,10,14,10,Urea
332,39.39,71.67,49.34,Black,Barley,35,0,0,10-26-26
333,35.79,67.64,45.04,Red,Barley,41,0,0,Urea
334,37.78,73.38,36.03,Black,Tobacco,10,3,30,DAP
335,31.38,48.73,62.27,Loamy,Millets,11,2,33,28-28

# 1.2 deep =False

In [11]:
# deep=Falges se (Any changes to the data of the original will be reflected in the shallow copy and vice-versa)
df_shallow_copy = df.copy(deep=False)

In [12]:
# update value in original dataframe
df.loc[4, 'Nitrogen'] = 15

In [13]:
# shallow copy vs original dataframe
df

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,29.96,55.46,24.12,Loamy,Cotton,8,19,16,Urea
1,36.83,69.28,25.17,Red,Wheat,17,0,28,28-28
2,26.95,60.64,35.66,Red,Barley,35,4,3,Urea
3,31.23,44.60,25.08,Red,Maize,17,3,12,DAP
4,33.78,51.39,40.00,Black,Cotton,15,9,34,28-28
...,...,...,...,...,...,...,...,...,...
331,35.30,59.61,44.25,Loamy,Oil seeds,10,14,10,Urea
332,39.39,71.67,49.34,Black,Barley,35,0,0,10-26-26
333,35.79,67.64,45.04,Red,Barley,41,0,0,Urea
334,37.78,73.38,36.03,Black,Tobacco,10,3,30,DAP
335,31.38,48.73,62.27,Loamy,Millets,11,2,33,28-28

In [14]:
df_shallow_copy

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,29.96,55.46,24.12,Loamy,Cotton,8,19,16,Urea
1,36.83,69.28,25.17,Red,Wheat,17,0,28,28-28
2,26.95,60.64,35.66,Red,Barley,35,4,3,Urea
3,31.23,44.60,25.08,Red,Maize,17,3,12,DAP
4,33.78,51.39,40.00,Black,Cotton,15,9,34,28-28
...,...,...,...,...,...,...,...,...,...
331,35.30,59.61,44.25,Loamy,Oil seeds,10,14,10,Urea
332,39.39,71.67,49.34,Black,Barley,35,0,0,10-26-26
333,35.79,67.64,45.04,Red,Barley,41,0,0,Urea
334,37.78,73.38,36.03,Black,Tobacco,10,3,30,DAP
335,31.38,48.73,62.27,Loamy,Millets,11,2,33,28-28

# 1.3 Simple Assignment

In [15]:
# make a ssignment
df_new_copy = df

In [17]:
# update value in original dataframe
df.loc[2,'Temparature'] = 30

In [18]:
# copy vs original dataframe
df

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,29.96,55.46,24.12,Loamy,Cotton,8,19,16,Urea
1,36.83,69.28,25.17,Red,Wheat,17,0,28,28-28
2,30.00,60.64,35.66,Red,Barley,35,4,3,Urea
3,31.23,44.60,25.08,Red,Maize,17,3,12,DAP
4,33.78,51.39,40.00,Black,Cotton,15,9,34,28-28
...,...,...,...,...,...,...,...,...,...
331,35.30,59.61,44.25,Loamy,Oil seeds,10,14,10,Urea
332,39.39,71.67,49.34,Black,Barley,35,0,0,10-26-26
333,35.79,67.64,45.04,Red,Barley,41,0,0,Urea
334,37.78,73.38,36.03,Black,Tobacco,10,3,30,DAP
335,31.38,48.73,62.27,Loamy,Millets,11,2,33,28-28

In [19]:
df_new_copy

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,29.96,55.46,24.12,Loamy,Cotton,8,19,16,Urea
1,36.83,69.28,25.17,Red,Wheat,17,0,28,28-28
2,30.00,60.64,35.66,Red,Barley,35,4,3,Urea
3,31.23,44.60,25.08,Red,Maize,17,3,12,DAP
4,33.78,51.39,40.00,Black,Cotton,15,9,34,28-28
...,...,...,...,...,...,...,...,...,...
331,35.30,59.61,44.25,Loamy,Oil seeds,10,14,10,Urea
332,39.39,71.67,49.34,Black,Barley,35,0,0,10-26-26
333,35.79,67.64,45.04,Red,Barley,41,0,0,Urea
334,37.78,73.38,36.03,Black,Tobacco,10,3,30,DAP
335,31.38,48.73,62.27,Loamy,Millets,11,2,33,28-28