In [1]:
import pandas as pd

In [2]:
df_cpcb_dataset = pd.read_csv('concrete.csv')

In [3]:
df_cpcb_dataset.head(4)

,cement,slag,ash,water,superplastic,coarseagg,fineagg,age,strength
0,141.3,212.0,0.0,203.5,0.0,971.8,748.5,28,29.89
1,168.9,42.2,124.3,158.3,10.8,1080.8,796.2,14,23.51
2,250.0,0.0,95.7,187.4,5.5,956.9,861.2,28,29.22
3,266.0,114.0,0.0,228.0,0.0,932.0,670.0,28,45.85

# 1. Create a column based on 1 conditions:
# np.where()

In [4]:
import numpy as np

In [5]:
# create as array based on strength tiers
df_cpcb_dataset['strength']>40

0       False
1       False
2       False
3        True
4       False
        ...
1025    False
1026     True
1027     True
1028     True
1029     True
Name: strength, Length: 1030, dtype: bool

In [12]:
np.where(df_cpcb_dataset['strength']>40,  'extremely high strength ','not for extremely severe condition')

array(['not for extremely severe condition',
       'not for extremely severe condition',
       'not for extremely severe condition', ...,
       'extremely high strength ', 'extremely high strength ',
       'extremely high strength '], dtype='<U34')

In [14]:
# set it to a new column
df_cpcb_dataset['strength_tiers'] = np.where(df_cpcb_dataset['strength']>40,  'extremely high strength ','not for extremely severe condition')

In [15]:
# show first 5 rows
df_cpcb_dataset.head()

,cement,slag,ash,water,superplastic,coarseagg,fineagg,age,strength,strength_tiers
0,141.3,212.0,0.0,203.5,0.0,971.8,748.5,28,29.89,not for extremely severe condition
1,168.9,42.2,124.3,158.3,10.8,1080.8,796.2,14,23.51,not for extremely severe condition
2,250.0,0.0,95.7,187.4,5.5,956.9,861.2,28,29.22,not for extremely severe condition
3,266.0,114.0,0.0,228.0,0.0,932.0,670.0,28,45.85,extremely high strength
4,154.8,183.4,0.0,193.3,9.1,1047.4,696.7,28,18.29,not for extremely severe condition

In [16]:
# count values in price_tier column
df_cpcb_dataset.value_counts('strength_tiers')

strength_tiers
not for extremely severe condition    651
extremely high strength               379
Name: count, dtype: int64

# 1.1 Excercise

In [20]:
# create an array based on conditions(age=>28)
np.where(df_cpcb_dataset['age']>=28, 'permanent setting', 'temporary setting')

array(['permanent setting', 'temporary setting', 'permanent setting', ...,
       'permanent setting', 'permanent setting', 'temporary setting'],
      dtype='<U17')

In [21]:
# set it to a new column
df_cpcb_dataset['setting type'] = np.where(df_cpcb_dataset['age']>=28, 'permanent setting', 'temporary setting')

In [22]:
# show first 5 rows
df_cpcb_dataset.head()

,cement,slag,ash,water,superplastic,coarseagg,fineagg,age,strength,strength_tiers,setting type
0,141.3,212.0,0.0,203.5,0.0,971.8,748.5,28,29.89,not for extremely severe condition,permanent setting
1,168.9,42.2,124.3,158.3,10.8,1080.8,796.2,14,23.51,not for extremely severe condition,temporary setting
2,250.0,0.0,95.7,187.4,5.5,956.9,861.2,28,29.22,not for extremely severe condition,permanent setting
3,266.0,114.0,0.0,228.0,0.0,932.0,670.0,28,45.85,extremely high strength,permanent setting
4,154.8,183.4,0.0,193.3,9.1,1047.4,696.7,28,18.29,not for extremely severe condition,permanent setting

In [24]:
# count values in setting_type column
df_cpcb_dataset.value_counts('setting type')

setting type
permanent setting    706
temporary setting    324
Name: count, dtype: int64