In [1]:
import pandas as pd

In [2]:
# read csv file
df = pd.read_csv('soil_geotech_data.csv')
# select columns
df = df[['Moisture','Crop Type','Nitrogen','Potassium','Phosphorous']]

In [3]:
# show dataframe
df

     Moisture  Crop Type  Nitrogen  Potassium  Phosphorous
0       24.12     Cotton         8         19           16
1       25.17      Wheat        17          0           28
2       35.66     Barley        35          4            3
3       25.08      Maize        17          3           12
4       47.60     Cotton         9          9           34
..        ...        ...       ...        ...          ...
331     44.25  Oil seeds        10         14           10
332     49.34     Barley        35          0            0
333     45.04     Barley        41          0            0
334     36.03    Tobacco        10          3           30
335     62.27    Millets        11          2           33

[336 rows x 5 columns]

# 1. Selecting with a single value
loc[row_label,column_label]

In [4]:
# get all data about index 55
df.loc[55]

Moisture        55.68
Crop Type      Barley
Nitrogen            8
Potassium          10
Phosphorous        14
Name: 55, dtype: object

In [5]:
df.loc[200]

Moisture       28.38
Crop Type      Wheat
Nitrogen          15
Potassium          4
Phosphorous        8
Name: 200, dtype: object

In [6]:
# get the Moisture of 75
df.loc[75,'Moisture']

np.float64(51.76)

In [7]:
# get the phosphorous of 89 index
df.loc[89,'Phosphorous']

np.int64(32)

In [8]:
# get all rows inside the 'Nitrogen' column
df.loc[:,'Nitrogen']

0       8
1      17
2      35
3      17
4       9
       ..
331    10
332    35
333    41
334    10
335    11
Name: Nitrogen, Length: 336, dtype: int64

In [9]:
# get all columns that correspond to the index 'loamy'
df.loc[45,:]

Moisture             32.53
Crop Type      Ground Nuts
Nitrogen                28
Potassium                0
Phosphorous             20
Name: 45, dtype: object

# 2. Selecting with a list of values

In [10]:
# get all data about 200 and 20
df.loc[[200,20]]

     Moisture  Crop Type  Nitrogen  Potassium  Phosphorous
200     28.38      Wheat        15          4            8
20      52.26  Sugarcane        25          1           22

In [11]:
# get the Crop Type of 99 and 56
df.loc[[99,56],'Crop Type']

99     Paddy
56    Barley
Name: Crop Type, dtype: object

In [12]:
# get the Phosphorous of 99 and 56
df.loc[[99,56],'Phosphorous']

99     0
56    37
Name: Phosphorous, dtype: int64

In [13]:
# get the Phosphorous and Nitrogen of 99
df.loc[[99],['Phosphorous','Nitrogen']]

    Phosphorous  Nitrogen
99            0        33

In [14]:
# get the Phosphorous and Nitrogen of 99 and 56
df.loc[[99,56],['Phosphorous','Nitrogen']]

    Phosphorous  Nitrogen
99            0        33
56           37        11

# 3. Selecting a range of data with a slice
start:stop:step(Note that contrary to usual pythonslices,both the start and stop are included )

In [16]:
# slice column labels
Crop_Type = [56,62]
df.loc[Crop_Type,'Nitrogen':'Phosphorous']

    Nitrogen  Potassium  Phosphorous
56        11          1           37
62        21          3           21

In [21]:
# slice index labels
columns = ['Moisture','Nitrogen','Potassium']
# get top1 and top10 index
df.index[:10]

df.loc[0:10, columns]

    Moisture  Nitrogen  Potassium
0      24.12         8         19
1      25.17        17          0
2      35.66        35          4
3      25.08        17          3
4      47.60         9          9
5      35.86        31          3
6      53.07         7         14
7      38.74        45          1
8      39.30         5         10
9      42.94        38          3
10     64.26         6          4

# 4. Selecting with conditions

In [29]:
# one condition: select player with Moisture below 23
columns =['Nitrogen','Moisture','Potassium','Phosphorous']

df.loc[df['Moisture']<23,columns]

     Nitrogen  Moisture  Potassium  Phosphorous
115         5     21.39         14           19
128        37     22.33          0            0
160        10     22.56          2            8
193         7     22.77          4           29
199        12     20.69         15           16
232         8     22.41          8           27
240        19     22.32         18           14
257         9     20.00          9           25
263        15     20.00          0           41
265        13     20.75         12           14
275         6     20.00          8           33
281        11     20.00         13           34
305        19     21.33         14           15

In [37]:
# multiple conditions: select Moisture <23  but Potassium>15
columns =['Nitrogen','Moisture','Potassium','Phosphorous']

df =df.loc[(df['Moisture']<23) & (df['Potassium']>15), :]

In [38]:
# show dataframe
df

     Moisture Crop Type  Nitrogen  Potassium  Phosphorous
240     22.32     Maize        19         18           14