In [1]:
import pandas as pd

# 1. Read a.csv from a URL with pandas
Target website https://www.football-data.co.uk/data.php

In [11]:
# reading ! csv file from the website
r21 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2526/E0.csv')

In [4]:
# showing dataframe
df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,E0,05/10/2025,14:00,Aston Villa,Burnley,2,1,H,1,0,...,1.95,1.90,2.15,1.78,2.08,1.95,1.92,1.86,1.99,2.00
66,E0,05/10/2025,14:00,Everton,Crystal Palace,2,1,H,0,1,...,1.88,1.98,1.83,2.11,1.88,2.02,1.82,1.96,1.93,2.06
67,E0,05/10/2025,14:00,Newcastle,Nott'm Forest,2,0,H,0,0,...,1.83,2.03,1.96,1.96,1.85,2.05,1.80,1.99,1.93,2.06
68,E0,05/10/2025,14:00,Wolves,Brighton,1,1,D,1,0,...,2.05,1.80,2.20,1.76,2.10,1.90,2.02,1.73,2.13,1.86
69,E0,05/10/2025,16:30,Brentford,Man City,0,1,A,0,1,...,1.75,2.05,1.84,2.10,1.81,2.05,1.78,2.01,1.86,2.15

In [5]:
# rename columns
df_premier21.rename(columns={'FTHG':'home goals',
                            'FTAG':'away goals'}, inplace=True)

In [6]:
# show dataframe
df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,home goals,away goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,E0,05/10/2025,14:00,Aston Villa,Burnley,2,1,H,1,0,...,1.95,1.90,2.15,1.78,2.08,1.95,1.92,1.86,1.99,2.00
66,E0,05/10/2025,14:00,Everton,Crystal Palace,2,1,H,0,1,...,1.88,1.98,1.83,2.11,1.88,2.02,1.82,1.96,1.93,2.06
67,E0,05/10/2025,14:00,Newcastle,Nott'm Forest,2,0,H,0,0,...,1.83,2.03,1.96,1.96,1.85,2.05,1.80,1.99,1.93,2.06
68,E0,05/10/2025,14:00,Wolves,Brighton,1,1,D,1,0,...,2.05,1.80,2.20,1.76,2.10,1.90,2.02,1.73,2.13,1.86
69,E0,05/10/2025,16:30,Brentford,Man City,0,1,A,0,1,...,1.75,2.05,1.84,2.10,1.81,2.05,1.78,2.01,1.86,2.15

# 2.Read .csv from Multiple URLs with pandas
https://www.football-data.co.uk/mmz4281/2526/E0.csv

https://www.football-data.co.uk/mmz4281/2526/E1.csv

https://www.football-data.co.uk/mmz4281/2526/E2.csv

Link : root + season + league

In [9]:
# link structure
"https://www.football-data.co.uk/mmz4281/" + "2526" + "/" + "E0" + ".csv"

'https://www.football-data.co.uk/mmz4281/2526/E0.csv'

In [12]:
# creating a root variable
root = "https://www.football-data.co.uk/mmz4281/"

# 2.1 Multiple leagues
 https://www.football-data.co.uk/mmz4281/2526/E0.csv     
 https://www.football-data.co.uk/mmz4281/2526/E1.csv    
 https://www.football-data.co.uk/mmz4281/2526/E2.csv    
 https://www.football-data.co.uk/mmz4281/2526/E3.csv    
 https://www.football-data.co.uk/mmz4281/2526/EC.csv

In [16]:
# creating list of leagues
leagues = ['E0', 'E1' , 'E2', 'E3', 'EC']
frames = []
# looping through leagues, read multiple csv and append it into a list
for league in leagues:
    df = pd.read_csv(root + '2526' + '/' + league + '.csv')
    frames.append(df)

In [17]:
# length of frames
len(frames)

5

In [19]:
# show 1st, 2nd and 3rd element
frames[4]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,EC,09/08/2025,15:00,Altrincham,Aldershot,3,2,H,2,0,...,1.90,1.90,1.92,1.93,1.90,1.90,1.86,1.84,2.00,1.99
1,EC,09/08/2025,15:00,Boreham Wood,Rochdale,0,2,A,0,0,...,2.00,1.80,2.05,1.82,2.02,1.80,1.96,1.75,2.06,1.89
2,EC,09/08/2025,15:00,Brackley Town,Eastleigh,1,0,H,1,0,...,2.00,1.80,2.14,1.72,2.03,1.80,1.96,1.75,2.06,1.84
3,EC,09/08/2025,15:00,Braintree Town,Halifax,3,0,H,2,0,...,1.93,1.88,1.97,1.88,1.93,1.88,1.88,1.82,1.97,1.98
4,EC,09/08/2025,15:00,Gateshead,Southend,0,3,A,0,1,...,1.83,1.98,1.67,2.19,1.83,2.04,1.75,1.96,1.84,2.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,EC,04/10/2025,15:00,Wealdstone,Altrincham,1,1,D,1,1,...,2.00,1.80,2.00,1.85,2.00,1.80,1.95,1.75,2.08,1.87
158,EC,04/10/2025,15:00,Woking,Truro,2,2,D,1,0,...,1.80,2.00,1.81,2.07,1.80,2.00,1.75,1.96,1.82,2.09
159,EC,04/10/2025,15:00,Yeovil,Boreham Wood,0,3,A,0,2,...,1.93,1.88,1.86,2.00,1.93,1.88,1.86,1.84,2.00,1.96
160,EC,04/10/2025,17:30,Scunthorpe,Carlisle,0,1,A,0,1,...,1.78,2.03,1.76,2.10,1.78,2.03,1.75,1.97,1.92,1.97
161,EC,07/10/2025,19:45,Scunthorpe,Morecambe,3,1,H,2,0,...,1.93,1.88,1.78,2.05,1.93,1.90,1.85,1.85,1.96,1.96

# 2.2 Multiple seasons

In [21]:
for season in range(19,25):
    print(str(season) + str(season+1))

1920
2021
2122
2223
2324
2425

In [25]:
# creating list of leagues
leagues = ['E0', 'E2', 'E3']
frames = []

# loop through range of seasons and insert new column
for league in leagues:
    for season in range(19,25):
        df = pd.read_csv(root + str(season) + str(season+1) + '/' + league + '.csv')
        df.insert(1, 'season', season)
        frames.append(df)

In [26]:
# total frames (6 seaspns by 3 leagues)
len(frames)

18

In [27]:
# show list, and last element (new season column was created)
frames[17]

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E3,24,09/08/2024,20:00,Chesterfield,Swindon,1,1,D,1,...,1.83,2.03,1.86,2.03,1.89,2.05,1.83,1.97,1.91,2.06
1,E3,24,10/08/2024,15:00,AFC Wimbledon,Colchester,4,2,H,3,...,1.75,2.05,1.83,2.07,1.83,2.17,1.76,2.05,1.86,2.12
2,E3,24,10/08/2024,15:00,Barrow,Crewe,1,0,H,1,...,1.88,1.98,1.87,2.02,1.90,2.04,1.84,1.95,1.88,2.09
3,E3,24,10/08/2024,15:00,Cheltenham,Newport County,3,2,H,2,...,1.93,1.93,1.96,1.93,1.98,1.96,1.91,1.88,2.05,1.92
4,E3,24,10/08/2024,15:00,Doncaster,Accrington,4,1,H,1,...,1.93,1.93,1.95,1.93,1.95,1.98,1.89,1.89,1.98,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E3,24,03/05/2025,15:00,Morecambe,Harrogate,1,2,A,1,...,1.78,2.10,1.74,2.12,1.78,2.18,1.73,2.09,1.81,2.22
548,E3,24,03/05/2025,15:00,Newport County,Tranmere,1,4,A,1,...,1.78,2.03,1.84,2.00,1.84,2.03,1.81,1.98,1.84,2.13
549,E3,24,03/05/2025,15:00,Notts County,Doncaster,1,2,A,0,...,1.80,2.05,1.79,2.06,1.81,2.12,1.76,2.05,1.85,2.15
550,E3,24,03/05/2025,15:00,Port Vale,Gillingham,0,1,A,0,...,2.03,1.83,2.04,1.81,2.05,1.83,2.00,1.80,2.09,1.86
551,E3,24,03/05/2025,15:00,Swindon,Milton Keynes Dons,0,0,D,0,...,2.03,1.83,1.99,1.85,2.04,1.86,1.98,1.83,2.11,1.86

# 3. Organise All the data in a dictionary

In [32]:
# create a dictinary with original name of leagueas key
dict_countries = {
    'spanish La Liga': 'SP1', 'Spanish Segunda Division': 'SP2', 'German Bundesliga': 'D1',
    'English Premier League': 'E0', 'English League 1': 'E2'
}

In [33]:
# get a dictionary element
dict_countries['spanish La Liga']

'SP1'

In [37]:
for league in dict_countries:
    print(dict_countries[league])

SP1
SP2
D1
E0
E2

In [41]:
dict_historical_data = {}

# creating list of leagues
# leagues = ['E0', 'E2', 'E3']


# looping through key elements
for league in dict_countries:
    frames = []
    for season in range(19,25):
        df = pd.read_csv(root + str(season) + str(season+1) + '/' + dict_countries[league] + '.csv')
        df.insert(1, 'season', season)
        frames.append(df)
    df_concat = pd.concat(frames)
    dict_historical_data[league] = df_concat

In [42]:
# show dataframe inside dict_historical_data
dict_historical_data.keys()

dict_keys(['spanish La Liga', 'Spanish Segunda Division', 'German Bundesliga', 'English Premier League', 'English League 1'])

In [45]:
dict_historical_data['English Premier League']

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,1XBCH,1XBCD,1XBCA,BFECH,BFECD,BFECA,BFEC>2.5,BFEC<2.5,BFECAHH,BFECAHA
0,E0,19,09/08/2019,20:00,Liverpool,Norwich,4,1,H,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,19,10/08/2019,12:30,West Ham,Man City,0,5,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,19,10/08/2019,15:00,Bournemouth,Sheffield United,1,1,D,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,19,10/08/2019,15:00,Burnley,Southampton,3,0,H,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,19,10/08/2019,15:00,Crystal Palace,Everton,0,0,D,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,24,25/05/2025,16:00,Newcastle,Everton,0,1,A,0,...,1.30,6.11,10.20,1.27,7.0,13.00,1.50,2.94,1.93,2.05
376,E0,24,25/05/2025,16:00,Nott'm Forest,Chelsea,0,1,A,0,...,3.50,3.86,2.06,3.55,3.9,2.14,1.76,2.28,1.86,2.14
377,E0,24,25/05/2025,16:00,Southampton,Arsenal,1,2,A,0,...,12.20,6.11,1.28,13.00,6.8,1.28,1.45,3.15,2.06,1.89
378,E0,24,25/05/2025,16:00,Tottenham,Brighton,1,4,A,1,...,3.63,4.12,1.95,3.95,4.2,1.93,1.51,2.92,2.06,1.93
379,E0,24,25/05/2025,16:00,Wolves,Brentford,1,1,D,0,...,2.98,3.80,2.31,3.05,3.8,2.42,1.54,2.78,1.89,2.10