In [3]:
import pandas as pd

In [4]:
df_cpcb_dataset = pd.read_csv('concrete.csv')

In [5]:
df_cpcb_dataset.head(4)

,cement,slag,ash,water,superplastic,coarseagg,fineagg,age,strength
0,141.3,212.0,0.0,203.5,0.0,971.8,748.5,28,29.89
1,168.9,42.2,124.3,158.3,10.8,1080.8,796.2,14,23.51
2,250.0,0.0,95.7,187.4,5.5,956.9,861.2,28,29.22
3,266.0,114.0,0.0,228.0,0.0,932.0,670.0,28,45.85

# 1. Filter dataframe based on a condition

In [6]:
# find 0.0 superplastic concrete
df_cpcb_dataset['superplastic'] == 0.0

0        True
1       False
2       False
3        True
4       False
        ...
1025    False
1026    False
1027    False
1028     True
1029     True
Name: superplastic, Length: 1030, dtype: bool

In [7]:
# find concrete that have superplasticity more than or equal to 7
df_cpcb_dataset['superplastic'] >= 7.0

0       False
1        True
2       False
3       False
4        True
        ...
1025     True
1026     True
1027     True
1028    False
1029    False
Name: superplastic, Length: 1030, dtype: bool

# 2. Filter dataframe based on multiple conditions

In [8]:
# find cement 250 that have superplastic more than  or equal to 7.0
(df_cpcb_dataset['cement']== 250) & (df_cpcb_dataset['superplastic'] >= 7.0)

0       False
1       False
2       False
3       False
4       False
        ...
1025    False
1026    False
1027    False
1028    False
1029    False
Length: 1030, dtype: bool

In [ ]:
and -> &
or -> |

# 2.1 & and

In [10]:
# filter dataframe based on multiple conditions
df_cpcb_dataset[(df_cpcb_dataset['cement']== 250) & (df_cpcb_dataset['superplastic'] >= 7.0)]

,cement,slag,ash,water,superplastic,coarseagg,fineagg,age,strength
824,250.0,180.0,95.0,159.0,9.5,860.0,800.0,28,67.87

# 2.2 | or

In [11]:
# find Cement 250 or 200
(df_cpcb_dataset['cement']== 250) | (df_cpcb_dataset['cement']== 200)

0       False
1       False
2        True
3       False
4       False
        ...
1025    False
1026    False
1027    False
1028    False
1029    False
Name: cement, Length: 1030, dtype: bool

In [26]:
# filter dataframe based on multiple conditions
df_cpcb_dataset[(df_cpcb_dataset['cement']== 250) | (df_cpcb_dataset['cement']== 200)].value_counts('cement')

cement
250.0    13
200.0     7
Name: count, dtype: int64

In [33]:
# filter dataframe based on multiple connditions
df_cpcb_dataset[((df_cpcb_dataset['cement']== 250) | (df_cpcb_dataset['cement']== 200)) ]

,cement,slag,ash,water,superplastic,coarseagg,fineagg,age,strength
2,250.0,0.0,95.7,187.4,5.5,956.9,861.2,28,29.22
50,200.0,200.0,0.0,190.0,0.0,1145.0,660.0,28,49.25
59,250.0,0.0,95.7,187.4,5.5,956.9,861.2,100,42.35
70,200.0,133.0,0.0,192.0,0.0,965.4,806.2,3,11.41
121,250.0,0.0,95.7,191.8,5.3,948.9,857.2,56,39.64
248,200.0,0.0,0.0,180.0,0.0,1125.0,845.0,28,12.25
358,250.0,0.0,95.7,187.4,5.5,956.9,861.2,14,24.92
422,250.0,0.0,95.7,187.4,5.5,956.9,861.2,3,13.82
618,250.0,0.0,95.7,187.4,5.5,956.9,861.2,56,38.33
626,200.0,133.0,0.0,192.0,0.0,965.4,806.2,90,43.25
650,250.0,0.0,95.7,191.8,5.3,948.9,857.2,3,8.49
659,250.0,0.0,0.0,182.0,0.0,1100.0,820.0,7,12.73
673,200.0,0.0,0.0,180.0,0.0,1125.0,845.0,7,7.84
812,250.0,0.0,95.7,191.8,5.3,948.9,857.2,14,24.66
818,250.0,0.0,0.0,182.0,0.0,1100.0,820.0,28,20.87
819,200.0,133.0,0.0,192.0,0.0,965.4,806.2,28,30.44
824,250.0,180.0,95.0,159.0,9.5,860.0,800.0,28,67.87
893,250.0,0.0,95.7,191.8,5.3,948.9,857.2,100,41.16
958,200.0,133.0,0.0,192.0,0.0,965.4,806.2,7,17.17
1004,250.0,0.0,95.7,191.8,5.3,948.9,857.2,28,27.22

In [37]:
# find Cement 250 or 200 having superplastic greater then 5.0
((df_cpcb_dataset['cement']== 250) | (df_cpcb_dataset['cement']== 200)) & (df_cpcb_dataset['superplastic'] >= 5.0)

0       False
1       False
2        True
3       False
4       False
        ...
1025    False
1026    False
1027    False
1028    False
1029    False
Length: 1030, dtype: bool

In [39]:
# filter dataframe based on multiple conditions
df_cpcb_dataset[((df_cpcb_dataset['cement']== 250) | (df_cpcb_dataset['cement']== 165)) & (df_cpcb_dataset['superplastic'] >= 5.0)]

,cement,slag,ash,water,superplastic,coarseagg,fineagg,age,strength
2,250.0,0.0,95.7,187.4,5.5,956.9,861.2,28,29.22
59,250.0,0.0,95.7,187.4,5.5,956.9,861.2,100,42.35
77,165.0,128.5,132.1,175.1,8.1,1005.8,746.6,3,19.42
121,250.0,0.0,95.7,191.8,5.3,948.9,857.2,56,39.64
358,250.0,0.0,95.7,187.4,5.5,956.9,861.2,14,24.92
399,165.0,128.5,132.1,175.1,8.1,1005.8,746.6,14,33.09
422,250.0,0.0,95.7,187.4,5.5,956.9,861.2,3,13.82
446,165.0,128.5,132.1,175.1,8.1,1005.8,746.6,100,55.02
544,165.0,0.0,150.0,182.0,12.0,1023.0,729.0,28,18.03
598,165.0,128.5,132.1,175.1,8.1,1005.8,746.6,56,53.72
618,250.0,0.0,95.7,187.4,5.5,956.9,861.2,56,38.33
650,250.0,0.0,95.7,191.8,5.3,948.9,857.2,3,8.49
812,250.0,0.0,95.7,191.8,5.3,948.9,857.2,14,24.66
814,165.0,128.5,132.1,175.1,8.1,1005.8,746.6,28,46.39
824,250.0,180.0,95.0,159.0,9.5,860.0,800.0,28,67.87
893,250.0,0.0,95.7,191.8,5.3,948.9,857.2,100,41.16
1004,250.0,0.0,95.7,191.8,5.3,948.9,857.2,28,27.22