In [2]:
import pandas as pd

In [3]:
# read csv file
df = pd.read_csv('soil_geotech_data.csv')
# select columns
df = df[['Moisture','Crop Type','Nitrogen','Potassium','Phosphorous']]

In [4]:
# show dataframe
df

     Moisture  Crop Type  Nitrogen  Potassium  Phosphorous
0       24.12     Cotton         8         19           16
1       25.17      Wheat        17          0           28
2       35.66     Barley        35          4            3
3       25.08      Maize        17          3           12
4       47.60     Cotton         9          9           34
..        ...        ...       ...        ...          ...
331     44.25  Oil seeds        10         14           10
332     49.34     Barley        35          0            0
333     45.04     Barley        41          0            0
334     36.03    Tobacco        10          3           30
335     62.27    Millets        11          2           33

[336 rows x 5 columns]

# 1. Selecting with a single value
iloc[row_position,column_position]

In [7]:
# get the potassium of index 45
df.loc[[45],'Potassium']

45    0
Name: Potassium, dtype: int64

In [17]:
df.iloc[45,3]

np.int64(0)

In [8]:
# get the Nitrogen of 102
df.loc[[102],'Nitrogen']

102    19
Name: Nitrogen, dtype: int64

In [18]:
df.iloc[102,2]

np.int64(19)

In [13]:
# get all rows inside the 'Nitrogen'
df.loc[:,'Nitrogen']

0       8
1      17
2      35
3      17
4       9
       ..
331    10
332    35
333    41
334    10
335    11
Name: Nitrogen, Length: 336, dtype: int64

In [20]:
df.iloc[:,2]

0       8
1      17
2      35
3      17
4       9
       ..
331    10
332    35
333    41
334    10
335    11
Name: Nitrogen, Length: 336, dtype: int64

In [14]:
# get all columns that correspond to the index '190'
df.loc[190,:]

Moisture       36.49
Crop Type      Maize
Nitrogen           4
Potassium         19
Phosphorous       12
Name: 190, dtype: object

In [21]:
df.iloc[190,:]

Moisture       36.49
Crop Type      Maize
Nitrogen           4
Potassium         19
Phosphorous       12
Name: 190, dtype: object

# 2. Selecting with a list of values

In [24]:
# get all data about 4 and 17

df.iloc[[4,17]]

    Moisture Crop Type  Nitrogen  Potassium  Phosphorous
4      47.60    Cotton         9          9           34
17     23.99     Wheat        15         15           14

In [26]:
# get the Moisture of 4 and 17
df.iloc[[4,17],0]

4     47.60
17    23.99
Name: Moisture, dtype: float64

In [29]:
# get the Moisture and Potassium of 4 
df.iloc[[4],[0,2]]

   Moisture  Nitrogen
4      47.6         9

In [30]:
# get Moisture and Potassium of 4 & 17
df.iloc[[4,17],[0,2]]

    Moisture  Nitrogen
4      47.60         9
17     23.99        15

# 3. Selecting a range of data with a slice
start:stop(Note the the start included but the stop is excluded)

In [31]:
df

     Moisture  Crop Type  Nitrogen  Potassium  Phosphorous
0       24.12     Cotton         8         19           16
1       25.17      Wheat        17          0           28
2       35.66     Barley        35          4            3
3       25.08      Maize        17          3           12
4       47.60     Cotton         9          9           34
..        ...        ...       ...        ...          ...
331     44.25  Oil seeds        10         14           10
332     49.34     Barley        35          0            0
333     45.04     Barley        41          0            0
334     36.03    Tobacco        10          3           30
335     62.27    Millets        11          2           33

[336 rows x 5 columns]

In [32]:
# slice column labels Moisture/Nitrogen
# index = [4,17]
index = [4,17]

df.iloc[index,0:2+1]

    Moisture Crop Type  Nitrogen
4      47.60    Cotton         9
17     23.99     Wheat        15

In [37]:
# slice index labels (top1 to top10 index)
# columns = ['Nitrogen','Potassium','Phosphorous']
index1 = [2,3,4]

# get top1 and top10 index
df.iloc[0:10,index1]

   Nitrogen  Potassium  Phosphorous
0         8         19           16
1        17          0           28
2        35          4            3
3        17          3           12
4         9          9           34
5        31          3            0
6         7         14           32
7        45          1            3
8         5         10           28
9        38          3            1

In [38]:
df.iloc[0:10,2:4+1]

   Nitrogen  Potassium  Phosphorous
0         8         19           16
1        17          0           28
2        35          4            3
3        17          3           12
4         9          9           34
5        31          3            0
6         7         14           32
7        45          1            3
8         5         10           28
9        38          3            1

# 4. Selecting with conditions
iloc cannot accept a boolean Series, but only a boolean list. We have to use the list() function to convert a series into a boolean list.

In [39]:
# one condition: select index with  phosphorous above 20
# columns = ['Moisture','Crop Type','Nitrogen']
columns = [1,2,3,4]

df.iloc[list(df['Phosphorous']>20), columns]

       Crop Type  Nitrogen  Potassium  Phosphorous
1          Wheat        17          0           28
4         Cotton         9          9           34
6      Sugarcane         7         14           32
8    Ground Nuts         5         10           28
11       Tobacco         6         13           28
..           ...       ...        ...          ...
325  Ground Nuts        14          5           33
328      Tobacco         6          4           37
329      Millets        13          4           42
334      Tobacco        10          3           30
335      Millets        11          2           33

[146 rows x 4 columns]

In [45]:
# multiple conditions : select index with Phosphorous above 40 and potassium == 0

df.iloc[list((df['Phosphorous']>40) & (df['Potassium']==0)), columns]

       Crop Type  Nitrogen  Potassium  Phosphorous
91       Tobacco        10          0           43
110       Pulses         8          0           42
145        Paddy        15          0           43
157    Sugarcane        10          0           43
215    Sugarcane        16          0           42
237        Wheat        12          0           41
263        Wheat        15          0           41
278       Barley        16          0           42
290       Barley        13          0           41
297  Ground Nuts         9          0           42