In [2]:
import pandas as pd

In [3]:
# reading the csv file
df_exams = pd.read_csv('rainfall_by_districts_2019.csv')

In [4]:
df_exams.shape

(33, 12)

In [6]:
pd.set_option('display.max_rows', None)

In [7]:
# showing the dataframe
df_exams

,S.No,District,Actual Rainfall in South West Monsoon (June'17 to September'17) in mm,Normal Rainfall in South West Monsoon (June'17 to September'17) in mm,Actual Rainfall in North East Monsoon (October'17 to December'17) in mm,Normal Rainfall in North East Monsoon (October'17 to December'17) in mm,Actual Rainfall in Winter Season (January'18 to and February'18) in mm,Normal Rainfall in Winter Season (January'18 to and February'18) in mm,Actual Rainfall in Hot Weather Season (March'18 to May'18) in mm,Normal Rainfall in Hot Weather Season (March'18 to May'18) in mm,Total Actual Rainfall (June'17 to May'18) in mm,Total Normal Rainfall (June'17 to May'18) in mm
0,1,Chennai,449.7,439.1,937.8,789.9,3.1,36.7,2.9,58.5,1393.5,1324.2
1,2,Kancheepuram,488.5,490.8,672.6,641.8,4.4,29.1,14.5,66.0,1180.0,1227.7
2,3,Tiruvallur,498.7,451.6,677.8,589.3,8.1,31.5,17.8,67.2,1202.4,1139.6
3,4,Cuddalore,465.7,383.1,775.9,697.8,55.0,44.1,14.4,81.7,1311.0,1206.7
4,5,Villupuram,441.3,408.3,535.7,499.1,10.5,28.2,24.2,76.0,1011.7,1011.6
5,6,Vellore,573.7,466.1,338.8,348.7,9.8,14.9,91.7,106.5,1014.0,936.2
6,7,Tiruvannamalai,621.9,468.1,524.9,446.5,34.9,26.5,52.4,98.9,1234.1,1040.0
7,8,Salem,484.7,440.6,341.9,370.5,15.4,16.0,179.2,170.8,1021.2,997.9
8,9,Namakkal,379.1,339.3,256.5,291.6,26.8,13.9,183.4,148.6,845.8,793.4
9,10,Dharmapuri,402.4,393.4,254.6,330.1,1.4,18.2,162.4,160.4,820.8,902.1
10,11,Krishnagiri,525.1,399.0,329.7,289.4,1.3,10.7,163.8,151.6,1019.9,850.7
11,12,Tiruppur,310.4,154.8,255.6,314.3,19.3,14.0,249.3,135.1,834.6,618.2
12,13,Coimbatore,510.0,189.8,182.6,328.9,12.8,20.3,311.8,150.3,1017.2,689.3
13,14,Erode,311.1,229.8,196.4,314.6,15.1,16.1,246.8,142.4,769.4,702.9
14,15,Tiruchirappalli,333.7,293.9,223.7,391.5,7.3,22.7,148.1,109.9,712.8,818.0
15,16,Karur,336.1,213.6,234.3,314.7,15.7,17.5,141.2,109.2,727.3,655.0
16,17,Perambalur,552.3,290.7,306.8,440.9,18.1,21.4,85.3,108.9,962.5,861.9
17,18,Pudukkottai,407.3,350.6,207.5,406.2,7.3,33.1,94.2,97.5,716.3,887.4
18,19,Thanjavur,479.5,318.4,433.7,550.3,21.9,42.3,59.4,102.1,994.5,1013.1
19,20,Tiruvarur,390.6,296.4,701.8,719.1,31.0,60.1,48.3,97.7,1171.7,1173.3
20,21,Nagapattinam,299.0,286.1,1132.3,941.0,78.8,85.7,19.7,80.5,1529.8,1393.3
21,22,Madurai,407.4,335.9,286.5,419.1,6.5,28.1,175.5,144.8,875.9,927.9
22,23,Theni,366.5,158.4,280.6,357.9,22.8,35.4,306.5,168.3,976.4,720.0
23,24,Dindigul,410.2,295.4,325.1,436.4,12.6,30.9,218.5,168.0,966.4,930.7
24,25,Ramanathapuram,211.3,149.3,259.1,491.7,2.2,51.3,110.8,115.5,583.4,807.8
25,26,Virudhunagar,293.6,196.8,332.3,419.0,28.5,42.8,238.0,161.5,892.4,820.1
26,27,Sivaganga,526.4,301.0,259.3,422.7,4.1,27.9,284.8,121.2,1074.6,872.8
27,28,Tirunelveli,212.6,142.4,665.5,467.2,25.8,69.3,247.8,166.2,1151.7,845.1
28,29,Thoothukudi,105.4,74.9,353.6,427.0,1.7,42.8,153.3,111.6,614.0,656.3
29,30,The Nilgiris,731.4,759.9,350.3,478.2,31.4,49.3,375.5,235.3,1488.6,1522.7
30,31,Ariyalur,549.4,392.0,491.7,545.5,25.8,32.5,52.2,101.8,1119.1,1071.8
31,32,Kanniyakumari,399.4,477.4,611.2,496.4,16.6,40.4,290.2,288.3,1317.4,1302.5
32,Average,State Average,421.1,330.8,429.3,468.0,18.0,32.9,148.9,128.2,1017.2,960.0

# 1 Attributes

In [8]:
# getting access to the shape attribute
df_exams.shape

(33, 12)

In [9]:
# getting access to the index attribute
df_exams.index

RangeIndex(start=0, stop=33, step=1)

In [11]:
# getting access to the columns attribute
df_exams.columns

Index(['S.No', 'District',
       'Actual Rainfall in South West Monsoon (June'17 to September'17) in mm',
       'Normal Rainfall in South West Monsoon (June'17 to September'17) in mm',
       'Actual Rainfall in North East Monsoon (October'17 to December'17) in mm',
       'Normal Rainfall in North East Monsoon (October'17 to December'17) in mm',
       'Actual Rainfall in Winter Season (January'18 to and February'18) in mm',
       'Normal Rainfall in Winter Season (January'18 to and February'18) in mm',
       'Actual Rainfall in Hot Weather Season (March'18 to May'18) in mm',
       'Normal Rainfall in Hot Weather Season (March'18 to May'18) in mm',
       'Total Actual Rainfall (June'17 to May'18) in mm',
       'Total Normal Rainfall (June'17 to May'18) in mm'],
      dtype='object')

In [12]:
# data types of each column
df_exams.dtypes

S.No                                                                        object
District                                                                    object
Actual Rainfall in South West Monsoon (June'17 to September'17) in mm      float64
Normal Rainfall in South West Monsoon (June'17 to September'17) in mm      float64
Actual Rainfall in North East Monsoon (October'17 to December'17) in mm    float64
Normal Rainfall in North East Monsoon (October'17 to December'17) in mm    float64
Actual Rainfall in Winter Season (January'18 to and February'18) in mm     float64
Normal Rainfall in Winter Season (January'18 to and February'18) in mm     float64
Actual Rainfall in Hot Weather Season (March'18 to May'18) in mm           float64
Normal Rainfall in Hot Weather Season (March'18 to May'18) in mm           float64
Total Actual Rainfall (June'17 to May'18) in mm                            float64
Total Normal Rainfall (June'17 to May'18) in mm                            float64
dtype: object

# 2 Methods

In [13]:
# showing the first 5 columns
df_exams.head()

,S.No,District,Actual Rainfall in South West Monsoon (June'17 to September'17) in mm,Normal Rainfall in South West Monsoon (June'17 to September'17) in mm,Actual Rainfall in North East Monsoon (October'17 to December'17) in mm,Normal Rainfall in North East Monsoon (October'17 to December'17) in mm,Actual Rainfall in Winter Season (January'18 to and February'18) in mm,Normal Rainfall in Winter Season (January'18 to and February'18) in mm,Actual Rainfall in Hot Weather Season (March'18 to May'18) in mm,Normal Rainfall in Hot Weather Season (March'18 to May'18) in mm,Total Actual Rainfall (June'17 to May'18) in mm,Total Normal Rainfall (June'17 to May'18) in mm
0,1,Chennai,449.7,439.1,937.8,789.9,3.1,36.7,2.9,58.5,1393.5,1324.2
1,2,Kancheepuram,488.5,490.8,672.6,641.8,4.4,29.1,14.5,66.0,1180.0,1227.7
2,3,Tiruvallur,498.7,451.6,677.8,589.3,8.1,31.5,17.8,67.2,1202.4,1139.6
3,4,Cuddalore,465.7,383.1,775.9,697.8,55.0,44.1,14.4,81.7,1311.0,1206.7
4,5,Villupuram,441.3,408.3,535.7,499.1,10.5,28.2,24.2,76.0,1011.7,1011.6

In [14]:
# showing the info of the dataframe
df_exams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 12 columns):
 #   Column                                                                   Non-Null Count  Dtype
---  ------                                                                   --------------  -----
 0   S.No                                                                     33 non-null     object
 1   District                                                                 33 non-null     object
 2   Actual Rainfall in South West Monsoon (June'17 to September'17) in mm    33 non-null     float64
 3   Normal Rainfall in South West Monsoon (June'17 to September'17) in mm    33 non-null     float64
 4   Actual Rainfall in North East Monsoon (October'17 to December'17) in mm  33 non-null     float64
 5   Normal Rainfall in North East Monsoon (October'17 to December'17) in mm  33 non-null     float64
 6   Actual Rainfall in Winter Season (January'18 to and February'18) in mm   33 non-null     float64
 7   Normal Rainfall in Winter Season (January'18 to and February'18) in mm   33 non-null     float64
 8   Actual Rainfall in Hot Weather Season (March'18 to May'18) in mm         33 non-null     float64
 9   Normal Rainfall in Hot Weather Season (March'18 to May'18) in mm         33 non-null     float64
 10  Total Actual Rainfall (June'17 to May'18) in mm                          33 non-null     float64
 11  Total Normal Rainfall (June'17 to May'18) in mm                          33 non-null     float64
dtypes: float64(10), object(2)
memory usage: 3.2+ KB

In [15]:
# describing basic statistics of the dataframe
df_exams.describe()

,Actual Rainfall in South West Monsoon (June'17 to September'17) in mm,Normal Rainfall in South West Monsoon (June'17 to September'17) in mm,Actual Rainfall in North East Monsoon (October'17 to December'17) in mm,Normal Rainfall in North East Monsoon (October'17 to December'17) in mm,Actual Rainfall in Winter Season (January'18 to and February'18) in mm,Normal Rainfall in Winter Season (January'18 to and February'18) in mm,Actual Rainfall in Hot Weather Season (March'18 to May'18) in mm,Normal Rainfall in Hot Weather Season (March'18 to May'18) in mm,Total Actual Rainfall (June'17 to May'18) in mm,Total Normal Rainfall (June'17 to May'18) in mm
count,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000
mean,421.075758,330.839394,429.254545,468.039394,18.000000,32.927273,148.872727,128.196970,1017.200000,960.006061
std,126.137440,136.145579,229.801495,151.207293,16.182977,16.798238,103.401252,47.899873,236.547749,225.942389
min,105.400000,74.900000,182.600000,289.400000,1.300000,10.700000,2.900000,58.500000,583.400000,618.200000
25%,336.100000,229.800000,259.100000,357.900000,7.300000,20.300000,52.400000,98.900000,845.800000,818.000000
50%,410.200000,330.800000,338.800000,436.400000,15.400000,30.900000,148.900000,115.500000,1014.000000,927.900000
75%,498.700000,408.300000,535.700000,499.100000,25.800000,42.300000,238.000000,151.600000,1171.700000,1071.800000
max,731.400000,759.900000,1132.300000,941.000000,78.800000,85.700000,375.500000,288.300000,1529.800000,1522.700000

# 3 Functions

In [16]:
# obtaining the length of the dataframe(number of columns)
len(df_exams)

33

In [18]:
# obtaining the highest index of the dataframe
max(df_exams.index)

32

In [ ]:
# obtaining the lowest index of the dataframe

In [19]:
min(df_exams.index)

0

In [20]:
# obtaining the datatype
type(df_exams)

pandas.core.frame.DataFrame

In [22]:
# rounding the value of the dataset
round(df_exams, 0)

,S.No,District,Actual Rainfall in South West Monsoon (June'17 to September'17) in mm,Normal Rainfall in South West Monsoon (June'17 to September'17) in mm,Actual Rainfall in North East Monsoon (October'17 to December'17) in mm,Normal Rainfall in North East Monsoon (October'17 to December'17) in mm,Actual Rainfall in Winter Season (January'18 to and February'18) in mm,Normal Rainfall in Winter Season (January'18 to and February'18) in mm,Actual Rainfall in Hot Weather Season (March'18 to May'18) in mm,Normal Rainfall in Hot Weather Season (March'18 to May'18) in mm,Total Actual Rainfall (June'17 to May'18) in mm,Total Normal Rainfall (June'17 to May'18) in mm
0,1,Chennai,450.0,439.0,938.0,790.0,3.0,37.0,3.0,58.0,1394.0,1324.0
1,2,Kancheepuram,488.0,491.0,673.0,642.0,4.0,29.0,14.0,66.0,1180.0,1228.0
2,3,Tiruvallur,499.0,452.0,678.0,589.0,8.0,32.0,18.0,67.0,1202.0,1140.0
3,4,Cuddalore,466.0,383.0,776.0,698.0,55.0,44.0,14.0,82.0,1311.0,1207.0
4,5,Villupuram,441.0,408.0,536.0,499.0,10.0,28.0,24.0,76.0,1012.0,1012.0
5,6,Vellore,574.0,466.0,339.0,349.0,10.0,15.0,92.0,106.0,1014.0,936.0
6,7,Tiruvannamalai,622.0,468.0,525.0,446.0,35.0,26.0,52.0,99.0,1234.0,1040.0
7,8,Salem,485.0,441.0,342.0,370.0,15.0,16.0,179.0,171.0,1021.0,998.0
8,9,Namakkal,379.0,339.0,256.0,292.0,27.0,14.0,183.0,149.0,846.0,793.0
9,10,Dharmapuri,402.0,393.0,255.0,330.0,1.0,18.0,162.0,160.0,821.0,902.0
10,11,Krishnagiri,525.0,399.0,330.0,289.0,1.0,11.0,164.0,152.0,1020.0,851.0
11,12,Tiruppur,310.0,155.0,256.0,314.0,19.0,14.0,249.0,135.0,835.0,618.0
12,13,Coimbatore,510.0,190.0,183.0,329.0,13.0,20.0,312.0,150.0,1017.0,689.0
13,14,Erode,311.0,230.0,196.0,315.0,15.0,16.0,247.0,142.0,769.0,703.0
14,15,Tiruchirappalli,334.0,294.0,224.0,392.0,7.0,23.0,148.0,110.0,713.0,818.0
15,16,Karur,336.0,214.0,234.0,315.0,16.0,18.0,141.0,109.0,727.0,655.0
16,17,Perambalur,552.0,291.0,307.0,441.0,18.0,21.0,85.0,109.0,962.0,862.0
17,18,Pudukkottai,407.0,351.0,208.0,406.0,7.0,33.0,94.0,98.0,716.0,887.0
18,19,Thanjavur,480.0,318.0,434.0,550.0,22.0,42.0,59.0,102.0,994.0,1013.0
19,20,Tiruvarur,391.0,296.0,702.0,719.0,31.0,60.0,48.0,98.0,1172.0,1173.0
20,21,Nagapattinam,299.0,286.0,1132.0,941.0,79.0,86.0,20.0,80.0,1530.0,1393.0
21,22,Madurai,407.0,336.0,286.0,419.0,6.0,28.0,176.0,145.0,876.0,928.0
22,23,Theni,366.0,158.0,281.0,358.0,23.0,35.0,306.0,168.0,976.0,720.0
23,24,Dindigul,410.0,295.0,325.0,436.0,13.0,31.0,218.0,168.0,966.0,931.0
24,25,Ramanathapuram,211.0,149.0,259.0,492.0,2.0,51.0,111.0,116.0,583.0,808.0
25,26,Virudhunagar,294.0,197.0,332.0,419.0,28.0,43.0,238.0,162.0,892.0,820.0
26,27,Sivaganga,526.0,301.0,259.0,423.0,4.0,28.0,285.0,121.0,1075.0,873.0
27,28,Tirunelveli,213.0,142.0,666.0,467.0,26.0,69.0,248.0,166.0,1152.0,845.0
28,29,Thoothukudi,105.0,75.0,354.0,427.0,2.0,43.0,153.0,112.0,614.0,656.0
29,30,The Nilgiris,731.0,760.0,350.0,478.0,31.0,49.0,376.0,235.0,1489.0,1523.0
30,31,Ariyalur,549.0,392.0,492.0,546.0,26.0,32.0,52.0,102.0,1119.0,1072.0
31,32,Kanniyakumari,399.0,477.0,611.0,496.0,17.0,40.0,290.0,288.0,1317.0,1302.0
32,Average,State Average,421.0,331.0,429.0,468.0,18.0,33.0,149.0,128.0,1017.0,960.0