In [1]:
import pandas as pd

In [2]:
df_cpcb_dataset = pd.read_csv('concrete.csv')

In [3]:
df_cpcb_dataset.head(4)

,cement,slag,ash,water,superplastic,coarseagg,fineagg,age,strength
0,141.3,212.0,0.0,203.5,0.0,971.8,748.5,28,29.89
1,168.9,42.2,124.3,158.3,10.8,1080.8,796.2,14,23.51
2,250.0,0.0,95.7,187.4,5.5,956.9,861.2,28,29.22
3,266.0,114.0,0.0,228.0,0.0,932.0,670.0,28,45.85

# 1. Creating a conditional Column from More Than 2 Choices: np.select()

In [4]:
import numpy as np

In [16]:
# create an array based on multiple price tiers (+2 choices)
# create "conditions" and "values" variables
conditions = [
    df_cpcb_dataset['strength']>40,
    (df_cpcb_dataset['strength']>35) & (df_cpcb_dataset['strength']<=40),
    (df_cpcb_dataset['strength']>30) & (df_cpcb_dataset['strength']<=35),
    (df_cpcb_dataset['strength']>25) & (df_cpcb_dataset['strength']<=30),
    (df_cpcb_dataset['strength']>20) & (df_cpcb_dataset['strength']<=25),
    df_cpcb_dataset['strength']<=20
]
values = ['for extreme conditions','for v.severe consitions','for severe conditions','for Moderate conditions','for severe conditions',' not for R.C.C use ']

In [18]:
df_cpcb_dataset['condition_category'] = np.select(conditions, values, default='unknown')

In [19]:
# show dataframe
df_cpcb_dataset

,cement,slag,ash,water,superplastic,coarseagg,fineagg,age,strength,condition_category
0,141.3,212.0,0.0,203.5,0.0,971.8,748.5,28,29.89,for Moderate conditions
1,168.9,42.2,124.3,158.3,10.8,1080.8,796.2,14,23.51,for severe conditions
2,250.0,0.0,95.7,187.4,5.5,956.9,861.2,28,29.22,for Moderate conditions
3,266.0,114.0,0.0,228.0,0.0,932.0,670.0,28,45.85,for extreme conditions
4,154.8,183.4,0.0,193.3,9.1,1047.4,696.7,28,18.29,not for R.C.C use
...,...,...,...,...,...,...,...,...,...,...
1025,135.0,0.0,166.0,180.0,10.0,961.0,805.0,28,13.29,not for R.C.C use
1026,531.3,0.0,0.0,141.8,28.2,852.1,893.7,3,41.30,for extreme conditions
1027,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28,for extreme conditions
1028,342.0,38.0,0.0,228.0,0.0,932.0,670.0,270,55.06,for extreme conditions
1029,540.0,0.0,0.0,173.0,0.0,1125.0,613.0,7,52.61,for extreme conditions

In [25]:
# count values inside "condition_category" column
df_cpcb_dataset.value_counts()

cement  slag   ash  water  superplastic  coarseagg  fineagg  age  strength  condition_category
362.6   189.0  0.0  164.9  11.6          944.7      755.8    3    35.30     for v.severe consitions    4
                                                             28   71.30     for extreme conditions     4
                                                             56   77.30     for extreme conditions     4
                                                             91   79.30     for extreme conditions     4
                                                             7    55.90     for extreme conditions     3
                                                                                                      ..
540.0   0.0    0.0  173.0  0.0           1125.0     613.0    14   59.76     for extreme conditions     1
                                                             28   67.31     for extreme conditions     1
                                                             90   69.66     for extreme conditions     1
                                                             180  71.62     for extreme conditions     1
102.0   153.0  0.0  192.0  0.0           887.0      942.0    3    4.57       not for R.C.C use         1
Name: count, Length: 1005, dtype: int64

In [26]:
# count values inside "condition_category" column
df_cpcb_dataset['condition_category'].value_counts()

condition_category
for extreme conditions     379
for severe conditions      223
 not for R.C.C use         197
for v.severe consitions    128
for Moderate conditions    103
Name: count, dtype: int64

In [27]:
df_cpcb_dataset.value_counts('condition_category')

condition_category
for extreme conditions     379
for severe conditions      223
 not for R.C.C use         197
for v.severe consitions    128
for Moderate conditions    103
Name: count, dtype: int64

# 2. Excercise

In [45]:
# create an array based on multiple cement content tiers (+2 choices)
# very high>500, 500>=High>400, 400>=Moderate>300, 300>=Low>200, very low<200
conditions = [
    df_cpcb_dataset['cement']>500,
    (df_cpcb_dataset['cement']>400) & (df_cpcb_dataset['cement']<=500),
    (df_cpcb_dataset['cement']>300) & (df_cpcb_dataset['cement']<=400),
    (df_cpcb_dataset['cement']>200) & (df_cpcb_dataset['cement']<=300),
    df_cpcb_dataset['cement']<200    
]

# create "conditions" and "values" variables
values  = ['Very High','High','Moderate','Low','Very Low']
values2 = ["special concrete(e.g., precast or dense waterproofing","High strength/water-resistant RCC",'RCC structural Conrete', "normal conrete(M20-M25)",'Lean conrete, weak binding']

In [54]:
# set it to a new column
RCC_meaning = "Reinforced Cement Conrete"
df_cpcb_dataset['cement_content_conditions'] = np.select(conditions, values, default='  RCC_meaning')

In [55]:
# show dataframe
df_cpcb_dataset

,cement,slag,ash,water,superplastic,coarseagg,fineagg,age,strength,condition_category,cement_content_conditions,cement_ RCC_meaning
0,141.3,212.0,0.0,203.5,0.0,971.8,748.5,28,29.89,for Moderate conditions,Very Low,"Lean conrete, weak binding"
1,168.9,42.2,124.3,158.3,10.8,1080.8,796.2,14,23.51,for severe conditions,Very Low,"Lean conrete, weak binding"
2,250.0,0.0,95.7,187.4,5.5,956.9,861.2,28,29.22,for Moderate conditions,Low,normal conrete(M20-M25)
3,266.0,114.0,0.0,228.0,0.0,932.0,670.0,28,45.85,for extreme conditions,Low,normal conrete(M20-M25)
4,154.8,183.4,0.0,193.3,9.1,1047.4,696.7,28,18.29,not for R.C.C use,Very Low,"Lean conrete, weak binding"
...,...,...,...,...,...,...,...,...,...,...,...,...
1025,135.0,0.0,166.0,180.0,10.0,961.0,805.0,28,13.29,not for R.C.C use,Very Low,"Lean conrete, weak binding"
1026,531.3,0.0,0.0,141.8,28.2,852.1,893.7,3,41.30,for extreme conditions,Very High,"special concrete(e.g., precast or dense waterp..."
1027,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28,for extreme conditions,Low,normal conrete(M20-M25)
1028,342.0,38.0,0.0,228.0,0.0,932.0,670.0,270,55.06,for extreme conditions,Moderate,RCC structural Conrete
1029,540.0,0.0,0.0,173.0,0.0,1125.0,613.0,7,52.61,for extreme conditions,Very High,"special concrete(e.g., precast or dense waterp..."

In [57]:
df_cpcb_dataset.value_counts('cement_content_conditions')

cement_content_conditions
Low              334
Moderate         277
Very Low         276
High             106
Very High         30
  RCC_meaning      7
Name: count, dtype: int64

In [48]:
df_cpcb_dataset['cement_ RCC_meaning'] = np.select(conditions,  values2, default=' unknown')

In [49]:
df_cpcb_dataset

,cement,slag,ash,water,superplastic,coarseagg,fineagg,age,strength,condition_category,cement_content_conditions,cement_ RCC_meaning
0,141.3,212.0,0.0,203.5,0.0,971.8,748.5,28,29.89,for Moderate conditions,Very Low,"Lean conrete, weak binding"
1,168.9,42.2,124.3,158.3,10.8,1080.8,796.2,14,23.51,for severe conditions,Very Low,"Lean conrete, weak binding"
2,250.0,0.0,95.7,187.4,5.5,956.9,861.2,28,29.22,for Moderate conditions,Low,normal conrete(M20-M25)
3,266.0,114.0,0.0,228.0,0.0,932.0,670.0,28,45.85,for extreme conditions,Low,normal conrete(M20-M25)
4,154.8,183.4,0.0,193.3,9.1,1047.4,696.7,28,18.29,not for R.C.C use,Very Low,"Lean conrete, weak binding"
...,...,...,...,...,...,...,...,...,...,...,...,...
1025,135.0,0.0,166.0,180.0,10.0,961.0,805.0,28,13.29,not for R.C.C use,Very Low,"Lean conrete, weak binding"
1026,531.3,0.0,0.0,141.8,28.2,852.1,893.7,3,41.30,for extreme conditions,Very High,"special concrete(e.g., precast or dense waterp..."
1027,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28,for extreme conditions,Low,normal conrete(M20-M25)
1028,342.0,38.0,0.0,228.0,0.0,932.0,670.0,270,55.06,for extreme conditions,Moderate,RCC structural Conrete
1029,540.0,0.0,0.0,173.0,0.0,1125.0,613.0,7,52.61,for extreme conditions,Very High,"special concrete(e.g., precast or dense waterp..."

In [50]:
# count values inside "screen_size" column
df_cpcb_dataset['cement_ RCC_meaning'].value_counts()

cement_ RCC_meaning
normal conrete(M20-M25)                                  334
RCC structural Conrete                                   277
Lean conrete, weak binding                               276
High strength/water-resistant RCC                        106
special concrete(e.g., precast or dense waterproofing     30
 unknown                                                   7
Name: count, dtype: int64