In [2]:
import pandas as pd

In [3]:
# read csv file
df = pd.read_csv('soil_geotech_data.csv')
# select columns
df = df[['Moisture','Crop Type','Nitrogen','Potassium','Phosphorous']]

In [4]:
# show dataframe
df

     Moisture  Crop Type  Nitrogen  Potassium  Phosphorous
0       24.12     Cotton         8         19           16
1       25.17      Wheat        17          0           28
2       35.66     Barley        35          4            3
3       25.08      Maize        17          3           12
4       47.60     Cotton         9          9           34
..        ...        ...       ...        ...          ...
331     44.25  Oil seeds        10         14           10
332     49.34     Barley        35          0            0
333     45.04     Barley        41          0            0
334     36.03    Tobacco        10          3           30
335     62.27    Millets        11          2           33

[336 rows x 5 columns]

# 1. Set value to one cell

In [7]:
# update 4 index Moisture
df.loc[4, 'Moisture'] = 40

In [8]:
# show dataframe
df

     Moisture Crop Type  Nitrogen  Potassium  Phosphorous
0       24.12    Cotton       8.0       19.0         16.0
1       25.17     Wheat      17.0        0.0         28.0
2       35.66    Barley      35.0        4.0          3.0
3       25.08     Maize      17.0        3.0         12.0
4       40.00    Cotton       9.0        9.0         34.0
..        ...       ...       ...        ...          ...
332     49.34    Barley      35.0        0.0          0.0
333     45.04    Barley      41.0        0.0          0.0
334     36.03   Tobacco      10.0        3.0         30.0
335     62.27   Millets      11.0        2.0         33.0
4       40.00       NaN       NaN        NaN          NaN

[337 rows x 5 columns]

# 2. Set value to entire column

In [12]:
# set Moisture of all index to 40
df.loc[:, 'Moisture'] = 40

In [13]:
# show dataframe
df

     Moisture Crop Type  Nitrogen  Potassium  Phosphorous
0        40.0    Cotton       8.0       19.0         16.0
1        40.0     Wheat      17.0        0.0         28.0
2        40.0    Barley      35.0        4.0          3.0
3        40.0     Maize      17.0        3.0         12.0
4        40.0    Cotton       9.0        9.0         34.0
..        ...       ...       ...        ...          ...
332      40.0    Barley      35.0        0.0          0.0
333      40.0    Barley      41.0        0.0          0.0
334      40.0   Tobacco      10.0        3.0         30.0
335      40.0   Millets      11.0        2.0         33.0
4        40.0       NaN       NaN        NaN          NaN

[337 rows x 5 columns]

# 3. Set value to entire row

In [16]:
# get all columns that correspond to moisture ranked last in soli geotech data
df.iloc[335, :]

Moisture          40.0
Crop Type      Millets
Nitrogen          11.0
Potassium          2.0
Phosphorous       33.0
Name: 335, dtype: object

In [17]:
df.iloc[-2,:]

Moisture          40.0
Crop Type      Millets
Nitrogen          11.0
Potassium          2.0
Phosphorous       33.0
Name: 335, dtype: object

In [20]:
#set null values to all columns that correspond to Moisture ranked last
import numpy as np

df.iloc[-2, :] = np.nan

In [21]:
# show dataframe
df

     Moisture Crop Type  Nitrogen  Potassium  Phosphorous
0        40.0    Cotton       8.0       19.0         16.0
1        40.0     Wheat      17.0        0.0         28.0
2        40.0    Barley      35.0        4.0          3.0
3        40.0     Maize      17.0        3.0         12.0
4        40.0    Cotton       9.0        9.0         34.0
..        ...       ...       ...        ...          ...
332      40.0    Barley      35.0        0.0          0.0
333      40.0    Barley      41.0        0.0          0.0
334      40.0   Tobacco      10.0        3.0         30.0
335       NaN       NaN       NaN        NaN          NaN
4         NaN       NaN       NaN        NaN          NaN

[337 rows x 5 columns]

# 4. Set value to MUltiple cells

In [24]:
# set value for all items matching the list of labels
df.loc[[4,334],['Moisture']] = 45

In [25]:
# show dataframe
df

     Moisture Crop Type  Nitrogen  Potassium  Phosphorous
0        40.0    Cotton       8.0       19.0         16.0
1        40.0     Wheat      17.0        0.0         28.0
2        40.0    Barley      35.0        4.0          3.0
3        40.0     Maize      17.0        3.0         12.0
4        45.0    Cotton       9.0        9.0         34.0
..        ...       ...       ...        ...          ...
332      40.0    Barley      35.0        0.0          0.0
333      40.0    Barley      41.0        0.0          0.0
334      45.0   Tobacco      10.0        3.0         30.0
335       NaN       NaN       NaN        NaN          NaN
4         NaN       NaN       NaN        NaN          NaN

[337 rows x 5 columns]

# 5. Set value for rows matching a condition

In [27]:
# set value for rows matching a condition
columns= ['Nitrogen','Potassium','Phosphorous']

df.loc[df['Nitrogen'] > 40, columns] =0

In [28]:
# show dataframe
df

     Moisture Crop Type  Nitrogen  Potassium  Phosphorous
0        40.0    Cotton       8.0       19.0         16.0
1        40.0     Wheat      17.0        0.0         28.0
2        40.0    Barley      35.0        4.0          3.0
3        40.0     Maize      17.0        3.0         12.0
4        45.0    Cotton       9.0        9.0         34.0
..        ...       ...       ...        ...          ...
332      40.0    Barley      35.0        0.0          0.0
333      40.0    Barley       0.0        0.0          0.0
334      45.0   Tobacco      10.0        3.0         30.0
335       NaN       NaN       NaN        NaN          NaN
4         NaN       NaN       NaN        NaN          NaN

[337 rows x 5 columns]