In [1]:
import pandas as pd

In [2]:
# read csv file
df = pd.read_csv('soil_geotech_data.csv')
# select columns
df = df[['Moisture','Crop Type','Nitrogen','Potassium','Phosphorous']]

In [3]:
# show dataframe
df

     Moisture  Crop Type  Nitrogen  Potassium  Phosphorous
0       24.12     Cotton         8         19           16
1       25.17      Wheat        17          0           28
2       35.66     Barley        35          4            3
3       25.08      Maize        17          3           12
4       47.60     Cotton         9          9           34
..        ...        ...       ...        ...          ...
331     44.25  Oil seeds        10         14           10
332     49.34     Barley        35          0            0
333     45.04     Barley        41          0            0
334     36.03    Tobacco        10          3           30
335     62.27    Millets        11          2           33

[336 rows x 5 columns]

# 1. Drop Row

In [5]:
# drop new row
# axis paramete
df.drop(1, axis=0)

     Moisture    Crop Type  Nitrogen  Potassium  Phosphorous
0       24.12       Cotton         8         19           16
2       35.66       Barley        35          4            3
3       25.08        Maize        17          3           12
4       47.60       Cotton         9          9           34
5       35.86  Ground Nuts        31          3            0
..        ...          ...       ...        ...          ...
331     44.25    Oil seeds        10         14           10
332     49.34       Barley        35          0            0
333     45.04       Barley        41          0            0
334     36.03      Tobacco        10          3           30
335     62.27      Millets        11          2           33

[335 rows x 5 columns]

In [7]:
# index parameter
df.drop(index=[2])

     Moisture    Crop Type  Nitrogen  Potassium  Phosphorous
0       24.12       Cotton         8         19           16
1       25.17        Wheat        17          0           28
3       25.08        Maize        17          3           12
4       47.60       Cotton         9          9           34
5       35.86  Ground Nuts        31          3            0
..        ...          ...       ...        ...          ...
331     44.25    Oil seeds        10         14           10
332     49.34       Barley        35          0            0
333     45.04       Barley        41          0            0
334     36.03      Tobacco        10          3           30
335     62.27      Millets        11          2           33

[335 rows x 5 columns]

In [8]:
# drop two or more row and update data (inplace=True)
df.drop([2,4], axis=0, inplace= True)

In [9]:
df

     Moisture    Crop Type  Nitrogen  Potassium  Phosphorous
0       24.12       Cotton         8         19           16
1       25.17        Wheat        17          0           28
3       25.08        Maize        17          3           12
5       35.86  Ground Nuts        31          3            0
6       53.07    Sugarcane         7         14           32
..        ...          ...       ...        ...          ...
331     44.25    Oil seeds        10         14           10
332     49.34       Barley        35          0            0
333     45.04       Barley        41          0            0
334     36.03      Tobacco        10          3           30
335     62.27      Millets        11          2           33

[334 rows x 5 columns]

# 2. Drop columns

In [11]:
# drop one column
# axis parameter
df.drop('Moisture', axis=1)

       Crop Type  Nitrogen  Potassium  Phosphorous
0         Cotton         8         19           16
1          Wheat        17          0           28
3          Maize        17          3           12
5    Ground Nuts        31          3            0
6      Sugarcane         7         14           32
..           ...       ...        ...          ...
331    Oil seeds        10         14           10
332       Barley        35          0            0
333       Barley        41          0            0
334      Tobacco        10          3           30
335      Millets        11          2           33

[334 rows x 4 columns]

In [14]:
# column parameter
df.drop(columns=['Moisture'])

       Crop Type  Nitrogen  Potassium  Phosphorous
0         Cotton         8         19           16
1          Wheat        17          0           28
3          Maize        17          3           12
5    Ground Nuts        31          3            0
6      Sugarcane         7         14           32
..           ...       ...        ...          ...
331    Oil seeds        10         14           10
332       Barley        35          0            0
333       Barley        41          0            0
334      Tobacco        10          3           30
335      Millets        11          2           33

[334 rows x 4 columns]

In [15]:
df

     Moisture    Crop Type  Nitrogen  Potassium  Phosphorous
0       24.12       Cotton         8         19           16
1       25.17        Wheat        17          0           28
3       25.08        Maize        17          3           12
5       35.86  Ground Nuts        31          3            0
6       53.07    Sugarcane         7         14           32
..        ...          ...       ...        ...          ...
331     44.25    Oil seeds        10         14           10
332     49.34       Barley        35          0            0
333     45.04       Barley        41          0            0
334     36.03      Tobacco        10          3           30
335     62.27      Millets        11          2           33

[334 rows x 5 columns]

In [19]:
# drop column by position/index (drop last column)

df.drop(df.columns[[-1]],axis=1)

     Moisture    Crop Type  Nitrogen  Potassium
0       24.12       Cotton         8         19
1       25.17        Wheat        17          0
3       25.08        Maize        17          3
5       35.86  Ground Nuts        31          3
6       53.07    Sugarcane         7         14
..        ...          ...       ...        ...
331     44.25    Oil seeds        10         14
332     49.34       Barley        35          0
333     45.04       Barley        41          0
334     36.03      Tobacco        10          3
335     62.27      Millets        11          2

[334 rows x 4 columns]

In [21]:
# drop two or more columns and update data (inplace=True)
df.drop(['Potassium','Nitrogen'], axis=1, inplace=True)

In [22]:
df

     Moisture    Crop Type  Phosphorous
0       24.12       Cotton           16
1       25.17        Wheat           28
3       25.08        Maize           12
5       35.86  Ground Nuts            0
6       53.07    Sugarcane           32
..        ...          ...          ...
331     44.25    Oil seeds           10
332     49.34       Barley            0
333     45.04       Barley            0
334     36.03      Tobacco           30
335     62.27      Millets           33

[334 rows x 3 columns]