In [2]:
import pandas as pd

In [3]:
# reading the csv file
df_exams = pd.read_csv('rainfall_by_districts_2019.csv')
df_exams.head()

,S.No,District,Actual Rainfall in South West Monsoon (June'17 to September'17) in mm,Normal Rainfall in South West Monsoon (June'17 to September'17) in mm,Actual Rainfall in North East Monsoon (October'17 to December'17) in mm,Normal Rainfall in North East Monsoon (October'17 to December'17) in mm,Actual Rainfall in Winter Season (January'18 to and February'18) in mm,Normal Rainfall in Winter Season (January'18 to and February'18) in mm,Actual Rainfall in Hot Weather Season (March'18 to May'18) in mm,Normal Rainfall in Hot Weather Season (March'18 to May'18) in mm,Total Actual Rainfall (June'17 to May'18) in mm,Total Normal Rainfall (June'17 to May'18) in mm
0,1,Chennai,449.7,439.1,937.8,789.9,3.1,36.7,2.9,58.5,1393.5,1324.2
1,2,Kancheepuram,488.5,490.8,672.6,641.8,4.4,29.1,14.5,66.0,1180.0,1227.7
2,3,Tiruvallur,498.7,451.6,677.8,589.3,8.1,31.5,17.8,67.2,1202.4,1139.6
3,4,Cuddalore,465.7,383.1,775.9,697.8,55.0,44.1,14.4,81.7,1311.0,1206.7
4,5,Villupuram,441.3,408.3,535.7,499.1,10.5,28.2,24.2,76.0,1011.7,1011.6

# 1 Adding a new column
# 1.1 Adding a new column with a scalar value

In [5]:
# adding new colummn to a dataframe
df_exams["Normal Rainfall in Winter Season (January'18 to and February'18) in mm"] = 33
df_exams

,S.No,District,Actual Rainfall in South West Monsoon (June'17 to September'17) in mm,Normal Rainfall in South West Monsoon (June'17 to September'17) in mm,Actual Rainfall in North East Monsoon (October'17 to December'17) in mm,Normal Rainfall in North East Monsoon (October'17 to December'17) in mm,Actual Rainfall in Winter Season (January'18 to and February'18) in mm,Normal Rainfall in Winter Season (January'18 to and February'18) in mm,Actual Rainfall in Hot Weather Season (March'18 to May'18) in mm,Normal Rainfall in Hot Weather Season (March'18 to May'18) in mm,Total Actual Rainfall (June'17 to May'18) in mm,Total Normal Rainfall (June'17 to May'18) in mm
0,1,Chennai,449.7,439.1,937.8,789.9,3.1,33,2.9,58.5,1393.5,1324.2
1,2,Kancheepuram,488.5,490.8,672.6,641.8,4.4,33,14.5,66.0,1180.0,1227.7
2,3,Tiruvallur,498.7,451.6,677.8,589.3,8.1,33,17.8,67.2,1202.4,1139.6
3,4,Cuddalore,465.7,383.1,775.9,697.8,55.0,33,14.4,81.7,1311.0,1206.7
4,5,Villupuram,441.3,408.3,535.7,499.1,10.5,33,24.2,76.0,1011.7,1011.6
5,6,Vellore,573.7,466.1,338.8,348.7,9.8,33,91.7,106.5,1014.0,936.2
6,7,Tiruvannamalai,621.9,468.1,524.9,446.5,34.9,33,52.4,98.9,1234.1,1040.0
7,8,Salem,484.7,440.6,341.9,370.5,15.4,33,179.2,170.8,1021.2,997.9
8,9,Namakkal,379.1,339.3,256.5,291.6,26.8,33,183.4,148.6,845.8,793.4
9,10,Dharmapuri,402.4,393.4,254.6,330.1,1.4,33,162.4,160.4,820.8,902.1
10,11,Krishnagiri,525.1,399.0,329.7,289.4,1.3,33,163.8,151.6,1019.9,850.7
11,12,Tiruppur,310.4,154.8,255.6,314.3,19.3,33,249.3,135.1,834.6,618.2
12,13,Coimbatore,510.0,189.8,182.6,328.9,12.8,33,311.8,150.3,1017.2,689.3
13,14,Erode,311.1,229.8,196.4,314.6,15.1,33,246.8,142.4,769.4,702.9
14,15,Tiruchirappalli,333.7,293.9,223.7,391.5,7.3,33,148.1,109.9,712.8,818.0
15,16,Karur,336.1,213.6,234.3,314.7,15.7,33,141.2,109.2,727.3,655.0
16,17,Perambalur,552.3,290.7,306.8,440.9,18.1,33,85.3,108.9,962.5,861.9
17,18,Pudukkottai,407.3,350.6,207.5,406.2,7.3,33,94.2,97.5,716.3,887.4
18,19,Thanjavur,479.5,318.4,433.7,550.3,21.9,33,59.4,102.1,994.5,1013.1
19,20,Tiruvarur,390.6,296.4,701.8,719.1,31.0,33,48.3,97.7,1171.7,1173.3
20,21,Nagapattinam,299.0,286.1,1132.3,941.0,78.8,33,19.7,80.5,1529.8,1393.3
21,22,Madurai,407.4,335.9,286.5,419.1,6.5,33,175.5,144.8,875.9,927.9
22,23,Theni,366.5,158.4,280.6,357.9,22.8,33,306.5,168.3,976.4,720.0
23,24,Dindigul,410.2,295.4,325.1,436.4,12.6,33,218.5,168.0,966.4,930.7
24,25,Ramanathapuram,211.3,149.3,259.1,491.7,2.2,33,110.8,115.5,583.4,807.8
25,26,Virudhunagar,293.6,196.8,332.3,419.0,28.5,33,238.0,161.5,892.4,820.1
26,27,Sivaganga,526.4,301.0,259.3,422.7,4.1,33,284.8,121.2,1074.6,872.8
27,28,Tirunelveli,212.6,142.4,665.5,467.2,25.8,33,247.8,166.2,1151.7,845.1
28,29,Thoothukudi,105.4,74.9,353.6,427.0,1.7,33,153.3,111.6,614.0,656.3
29,30,The Nilgiris,731.4,759.9,350.3,478.2,31.4,33,375.5,235.3,1488.6,1522.7
30,31,Ariyalur,549.4,392.0,491.7,545.5,25.8,33,52.2,101.8,1119.1,1071.8
31,32,Kanniyakumari,399.4,477.4,611.2,496.4,16.6,33,290.2,288.3,1317.4,1302.5
32,Average,State Average,421.1,330.8,429.3,468.0,18.0,33,148.9,128.2,1017.2,960.0

# 1.2 Adding a new column with an array
The dataframe has 32 rows so we need to create an array with 32 elememts

In [6]:
# import numpy
import numpy as np

In [14]:
# create an array of 33 elements
rainfall_data = np.arange(0,33)

In [15]:
# length of the array
len(np.arange(0,33))

33

In [16]:
# adding a new column to dataframe with an array
df_exams['rainfall_data'] = rainfall_data
df_exams

,S.No,District,Actual Rainfall in South West Monsoon (June'17 to September'17) in mm,Normal Rainfall in South West Monsoon (June'17 to September'17) in mm,Actual Rainfall in North East Monsoon (October'17 to December'17) in mm,Normal Rainfall in North East Monsoon (October'17 to December'17) in mm,Actual Rainfall in Winter Season (January'18 to and February'18) in mm,Normal Rainfall in Winter Season (January'18 to and February'18) in mm,Actual Rainfall in Hot Weather Season (March'18 to May'18) in mm,Normal Rainfall in Hot Weather Season (March'18 to May'18) in mm,Total Actual Rainfall (June'17 to May'18) in mm,Total Normal Rainfall (June'17 to May'18) in mm,rainfall_data
0,1,Chennai,449.7,439.1,937.8,789.9,3.1,33,2.9,58.5,1393.5,1324.2,0
1,2,Kancheepuram,488.5,490.8,672.6,641.8,4.4,33,14.5,66.0,1180.0,1227.7,1
2,3,Tiruvallur,498.7,451.6,677.8,589.3,8.1,33,17.8,67.2,1202.4,1139.6,2
3,4,Cuddalore,465.7,383.1,775.9,697.8,55.0,33,14.4,81.7,1311.0,1206.7,3
4,5,Villupuram,441.3,408.3,535.7,499.1,10.5,33,24.2,76.0,1011.7,1011.6,4
5,6,Vellore,573.7,466.1,338.8,348.7,9.8,33,91.7,106.5,1014.0,936.2,5
6,7,Tiruvannamalai,621.9,468.1,524.9,446.5,34.9,33,52.4,98.9,1234.1,1040.0,6
7,8,Salem,484.7,440.6,341.9,370.5,15.4,33,179.2,170.8,1021.2,997.9,7
8,9,Namakkal,379.1,339.3,256.5,291.6,26.8,33,183.4,148.6,845.8,793.4,8
9,10,Dharmapuri,402.4,393.4,254.6,330.1,1.4,33,162.4,160.4,820.8,902.1,9
10,11,Krishnagiri,525.1,399.0,329.7,289.4,1.3,33,163.8,151.6,1019.9,850.7,10
11,12,Tiruppur,310.4,154.8,255.6,314.3,19.3,33,249.3,135.1,834.6,618.2,11
12,13,Coimbatore,510.0,189.8,182.6,328.9,12.8,33,311.8,150.3,1017.2,689.3,12
13,14,Erode,311.1,229.8,196.4,314.6,15.1,33,246.8,142.4,769.4,702.9,13
14,15,Tiruchirappalli,333.7,293.9,223.7,391.5,7.3,33,148.1,109.9,712.8,818.0,14
15,16,Karur,336.1,213.6,234.3,314.7,15.7,33,141.2,109.2,727.3,655.0,15
16,17,Perambalur,552.3,290.7,306.8,440.9,18.1,33,85.3,108.9,962.5,861.9,16
17,18,Pudukkottai,407.3,350.6,207.5,406.2,7.3,33,94.2,97.5,716.3,887.4,17
18,19,Thanjavur,479.5,318.4,433.7,550.3,21.9,33,59.4,102.1,994.5,1013.1,18
19,20,Tiruvarur,390.6,296.4,701.8,719.1,31.0,33,48.3,97.7,1171.7,1173.3,19
20,21,Nagapattinam,299.0,286.1,1132.3,941.0,78.8,33,19.7,80.5,1529.8,1393.3,20
21,22,Madurai,407.4,335.9,286.5,419.1,6.5,33,175.5,144.8,875.9,927.9,21
22,23,Theni,366.5,158.4,280.6,357.9,22.8,33,306.5,168.3,976.4,720.0,22
23,24,Dindigul,410.2,295.4,325.1,436.4,12.6,33,218.5,168.0,966.4,930.7,23
24,25,Ramanathapuram,211.3,149.3,259.1,491.7,2.2,33,110.8,115.5,583.4,807.8,24
25,26,Virudhunagar,293.6,196.8,332.3,419.0,28.5,33,238.0,161.5,892.4,820.1,25
26,27,Sivaganga,526.4,301.0,259.3,422.7,4.1,33,284.8,121.2,1074.6,872.8,26
27,28,Tirunelveli,212.6,142.4,665.5,467.2,25.8,33,247.8,166.2,1151.7,845.1,27
28,29,Thoothukudi,105.4,74.9,353.6,427.0,1.7,33,153.3,111.6,614.0,656.3,28
29,30,The Nilgiris,731.4,759.9,350.3,478.2,31.4,33,375.5,235.3,1488.6,1522.7,29
30,31,Ariyalur,549.4,392.0,491.7,545.5,25.8,33,52.2,101.8,1119.1,1071.8,30
31,32,Kanniyakumari,399.4,477.4,611.2,496.4,16.6,33,290.2,288.3,1317.4,1302.5,31
32,Average,State Average,421.1,330.8,429.3,468.0,18.0,33,148.9,128.2,1017.2,960.0,32

In [25]:
# create random integer numbers between 1 and 33
np.random.randint(1,100, size = 33)

array([12, 73, 17, 29, 38, 44,  2, 32, 81, 73, 97, 99, 57, 98, 63, 84, 58,
       11,  4, 62, 87, 37, 36, 17, 32, 37, 70,  2, 57, 90, 43, 54, 11],
      dtype=int32)

In [26]:
len(np.random.randint(1,100, size = 33))

33

In [27]:
int_rainfall_data = np.random.randint(1,100, size = 33)

In [28]:
# min value inclusive and high value exclusive
min(int_rainfall_data)
max(int_rainfall_data)

np.int32(97)

In [29]:
# adding a new column to dataframe withan array
df_exams['rainfall_data'] = int_rainfall_data
df_exams

,S.No,District,Actual Rainfall in South West Monsoon (June'17 to September'17) in mm,Normal Rainfall in South West Monsoon (June'17 to September'17) in mm,Actual Rainfall in North East Monsoon (October'17 to December'17) in mm,Normal Rainfall in North East Monsoon (October'17 to December'17) in mm,Actual Rainfall in Winter Season (January'18 to and February'18) in mm,Normal Rainfall in Winter Season (January'18 to and February'18) in mm,Actual Rainfall in Hot Weather Season (March'18 to May'18) in mm,Normal Rainfall in Hot Weather Season (March'18 to May'18) in mm,Total Actual Rainfall (June'17 to May'18) in mm,Total Normal Rainfall (June'17 to May'18) in mm,rainfall_data
0,1,Chennai,449.7,439.1,937.8,789.9,3.1,33,2.9,58.5,1393.5,1324.2,45
1,2,Kancheepuram,488.5,490.8,672.6,641.8,4.4,33,14.5,66.0,1180.0,1227.7,81
2,3,Tiruvallur,498.7,451.6,677.8,589.3,8.1,33,17.8,67.2,1202.4,1139.6,78
3,4,Cuddalore,465.7,383.1,775.9,697.8,55.0,33,14.4,81.7,1311.0,1206.7,82
4,5,Villupuram,441.3,408.3,535.7,499.1,10.5,33,24.2,76.0,1011.7,1011.6,7
5,6,Vellore,573.7,466.1,338.8,348.7,9.8,33,91.7,106.5,1014.0,936.2,97
6,7,Tiruvannamalai,621.9,468.1,524.9,446.5,34.9,33,52.4,98.9,1234.1,1040.0,91
7,8,Salem,484.7,440.6,341.9,370.5,15.4,33,179.2,170.8,1021.2,997.9,16
8,9,Namakkal,379.1,339.3,256.5,291.6,26.8,33,183.4,148.6,845.8,793.4,41
9,10,Dharmapuri,402.4,393.4,254.6,330.1,1.4,33,162.4,160.4,820.8,902.1,31
10,11,Krishnagiri,525.1,399.0,329.7,289.4,1.3,33,163.8,151.6,1019.9,850.7,4
11,12,Tiruppur,310.4,154.8,255.6,314.3,19.3,33,249.3,135.1,834.6,618.2,24
12,13,Coimbatore,510.0,189.8,182.6,328.9,12.8,33,311.8,150.3,1017.2,689.3,93
13,14,Erode,311.1,229.8,196.4,314.6,15.1,33,246.8,142.4,769.4,702.9,27
14,15,Tiruchirappalli,333.7,293.9,223.7,391.5,7.3,33,148.1,109.9,712.8,818.0,87
15,16,Karur,336.1,213.6,234.3,314.7,15.7,33,141.2,109.2,727.3,655.0,6
16,17,Perambalur,552.3,290.7,306.8,440.9,18.1,33,85.3,108.9,962.5,861.9,31
17,18,Pudukkottai,407.3,350.6,207.5,406.2,7.3,33,94.2,97.5,716.3,887.4,35
18,19,Thanjavur,479.5,318.4,433.7,550.3,21.9,33,59.4,102.1,994.5,1013.1,96
19,20,Tiruvarur,390.6,296.4,701.8,719.1,31.0,33,48.3,97.7,1171.7,1173.3,82
20,21,Nagapattinam,299.0,286.1,1132.3,941.0,78.8,33,19.7,80.5,1529.8,1393.3,95
21,22,Madurai,407.4,335.9,286.5,419.1,6.5,33,175.5,144.8,875.9,927.9,9
22,23,Theni,366.5,158.4,280.6,357.9,22.8,33,306.5,168.3,976.4,720.0,68
23,24,Dindigul,410.2,295.4,325.1,436.4,12.6,33,218.5,168.0,966.4,930.7,92
24,25,Ramanathapuram,211.3,149.3,259.1,491.7,2.2,33,110.8,115.5,583.4,807.8,8
25,26,Virudhunagar,293.6,196.8,332.3,419.0,28.5,33,238.0,161.5,892.4,820.1,55
26,27,Sivaganga,526.4,301.0,259.3,422.7,4.1,33,284.8,121.2,1074.6,872.8,91
27,28,Tirunelveli,212.6,142.4,665.5,467.2,25.8,33,247.8,166.2,1151.7,845.1,20
28,29,Thoothukudi,105.4,74.9,353.6,427.0,1.7,33,153.3,111.6,614.0,656.3,72
29,30,The Nilgiris,731.4,759.9,350.3,478.2,31.4,33,375.5,235.3,1488.6,1522.7,22
30,31,Ariyalur,549.4,392.0,491.7,545.5,25.8,33,52.2,101.8,1119.1,1071.8,78
31,32,Kanniyakumari,399.4,477.4,611.2,496.4,16.6,33,290.2,288.3,1317.4,1302.5,79
32,Average,State Average,421.1,330.8,429.3,468.0,18.0,33,148.9,128.2,1017.2,960.0,67

In [31]:
# create random float numbers between 1 and 100
np.random.uniform(1,100,size=33)

array([83.08873234, 61.38488346, 16.8712835 , 94.13456782, 92.84528094,
       12.08294337, 84.57346075, 19.19548449, 22.63861536, 39.43185496,
       23.20188011, 74.0000694 ,  9.36062236, 73.69913269, 28.85889902,
       64.84190627, 30.21171409,  9.84991413, 10.01671053, 25.08669489,
       83.56250221, 78.24969263, 58.08911088, 52.35171643, 43.09655084,
       87.45679807, 58.76047758, 74.62396417, 10.42779624, 89.44298842,
        3.85779406, 34.32032788, 88.44224465])