In [1]:
import pandas as pd

In [2]:
# read csv file
df = pd.read_csv('soil_geotech_data.csv')
# select columns
df = df[['Moisture','Crop Type','Nitrogen','Potassium','Phosphorous']]

In [3]:
# show dataframe
df

     Moisture  Crop Type  Nitrogen  Potassium  Phosphorous
0       24.12     Cotton         8         19           16
1       25.17      Wheat        17          0           28
2       35.66     Barley        35          4            3
3       25.08      Maize        17          3           12
4       47.60     Cotton         9          9           34
..        ...        ...       ...        ...          ...
331     44.25  Oil seeds        10         14           10
332     49.34     Barley        35          0            0
333     45.04     Barley        41          0            0
334     36.03    Tobacco        10          3           30
335     62.27    Millets        11          2           33

[336 rows x 5 columns]

# 1. sample()

In [18]:
# extract 10 random elements from the "nationality" column
df['Crop Type'].sample(10, random_state=9)

172       Cotton
101       Barley
152        Paddy
280       Pulses
53     Oil seeds
231      Tobacco
31       Tobacco
151        Wheat
160       Pulses
197      Millets
Name: Crop Type, dtype: object

In [24]:
# extract a random 20% sample of the dataframe , new values everytime we run
df.sample(frac=0.2)

     Moisture    Crop Type  Nitrogen  Potassium  Phosphorous
281     20.00    Oil seeds        11         13           34
186     60.84  Ground Nuts        11          1           38
43      37.32    Sugarcane        11          2           39
190     36.49        Maize         4         19           12
114     32.94       Cotton         8         12           14
..        ...          ...       ...        ...          ...
268     50.47  Ground Nuts         7          5           28
267     46.87        Wheat         6         13           26
121     35.24       Cotton        13          0           37
68      69.57       Cotton        11          0           38
168     34.97    Oil seeds        12          0           10

[67 rows x 5 columns]

In [26]:
df.sample(frac=0.05, random_state=20)

     Moisture    Crop Type  Nitrogen  Potassium  Phosphorous
195     30.95       Cotton        12          4           15
119     53.96        Wheat         6          4           19
109     36.21       Barley        30          0            0
89      31.40       Pulses         9          4           32
104     55.68      Millets        14          0           12
299     53.13        Paddy        34          3            4
179     36.33        Wheat        23          0           21
61      32.87       Cotton         5          4           30
129     32.98       Cotton        12          2            9
292     48.45       Cotton        37          0            0
110     38.68       Pulses         8          0           42
112     30.71    Sugarcane        41          0            0
291     29.17    Sugarcane        34          3            0
305     21.33  Ground Nuts        19         14           15
208     62.07        Maize        11          2            8
108     24.95  Ground Nuts        43          0            0
335     62.27      Millets        11          2           33

In [32]:
# upsample: increase the sampling rate -> frac>1 (Note: replace  parameter has to be True for frac parameter > 1)

df.sample(frac=2,replace=True, random_state=99)

     Moisture  Crop Type  Nitrogen  Potassium  Phosphorous
129     32.98     Cotton        12          2            9
35      40.46     Pulses        20          2           23
185     32.95     Barley        36          2            4
168     34.97  Oil seeds        12          0           10
201     25.42  Sugarcane        10          0           38
..        ...        ...       ...        ...          ...
326     37.02     Cotton        20          3           19
318     53.68      Maize        21          0           18
51      33.97      Maize        10          1            5
99      24.05      Paddy        33          0            0
135     57.27    Millets         9         15            8

[672 rows x 5 columns]