In [1]:
import pandas as pd

In [2]:
# read csv file
df = pd.read_csv('soil_geotech_data.csv')
# select columns
df = df[['Moisture','Crop Type','Nitrogen','Potassium','Phosphorous']]

In [3]:
# show dataframe
df

     Moisture  Crop Type  Nitrogen  Potassium  Phosphorous
0       24.12     Cotton         8         19           16
1       25.17      Wheat        17          0           28
2       35.66     Barley        35          4            3
3       25.08      Maize        17          3           12
4       47.60     Cotton         9          9           34
..        ...        ...       ...        ...          ...
331     44.25  Oil seeds        10         14           10
332     49.34     Barley        35          0            0
333     45.04     Barley        41          0            0
334     36.03    Tobacco        10          3           30
335     62.27    Millets        11          2           33

[336 rows x 5 columns]

# 1. query()

In [9]:
# select index with moisture > 69
df.query('Moisture>69')

     Moisture  Crop Type  Nitrogen  Potassium  Phosphorous
31      69.64    Tobacco        41          0            3
68      69.57     Cotton        11          0           38
178     70.00    Millets         5          0           10
214     70.00     Barley        19          0           22
239     70.00  Oil seeds        35          0            0

In [11]:
# excercise : write the equivlent boolean slicing
df[df['Moisture']>69]

     Moisture  Crop Type  Nitrogen  Potassium  Phosphorous
31      69.64    Tobacco        41          0            3
68      69.57     Cotton        11          0           38
178     70.00    Millets         5          0           10
214     70.00     Barley        19          0           22
239     70.00  Oil seeds        35          0            0

In [23]:
# select index with moisture > 69 From Cotto
# excercise : write the equivalence boolean slicing
df.query ("Moisture>69 and 'Crop Type'=='Cotton'")

Empty DataFrame
Columns: [Moisture, Crop Type, Nitrogen, Potassium, Phosphorous]
Index: []

In [26]:
# excercise : write the equivalence boolean slicing
df[ (df["Moisture"]>69 ) & (df['Crop Type']=='Cotton')]

    Moisture Crop Type  Nitrogen  Potassium  Phosphorous
68     69.57    Cotton        11          0           38

In [30]:
# add a not operator to the first example
df.query('not(Moisture>69)')

     Moisture  Crop Type  Nitrogen  Potassium  Phosphorous
0       24.12     Cotton         8         19           16
1       25.17      Wheat        17          0           28
2       35.66     Barley        35          4            3
3       25.08      Maize        17          3           12
4       47.60     Cotton         9          9           34
..        ...        ...       ...        ...          ...
331     44.25  Oil seeds        10         14           10
332     49.34     Barley        35          0            0
333     45.04     Barley        41          0            0
334     36.03    Tobacco        10          3           30
335     62.27    Millets        11          2           33

[331 rows x 5 columns]

In [33]:
# excercise: write the eauivalent boolean slicing
df[~(df['Moisture']>69)]

     Moisture  Crop Type  Nitrogen  Potassium  Phosphorous
0       24.12     Cotton         8         19           16
1       25.17      Wheat        17          0           28
2       35.66     Barley        35          4            3
3       25.08      Maize        17          3           12
4       47.60     Cotton         9          9           34
..        ...        ...       ...        ...          ...
331     44.25  Oil seeds        10         14           10
332     49.34     Barley        35          0            0
333     45.04     Barley        41          0            0
334     36.03    Tobacco        10          3           30
335     62.27    Millets        11          2           33

[331 rows x 5 columns]

In [37]:
# convert Nitrogen to fraction upto 1 and select those with Nitrogen> 0.4
df.query("Nitrogen/100 > 0.4")
# excercise: write the eauivalent boolean slicing
df[df["Nitrogen"]/100>0.4]

     Moisture    Crop Type  Nitrogen  Potassium  Phosphorous
7       38.74    Oil seeds        45          1            3
31      69.64      Tobacco        41          0            3
74      43.02       Barley        45          0            0
107     33.59      Millets        41          0            0
108     24.95  Ground Nuts        43          0            0
112     30.71    Sugarcane        41          0            0
189     25.98        Paddy        41          4            1
212     55.39  Ground Nuts        43          0            4
247     24.19        Wheat        41          0            0
301     38.50    Oil seeds        46          3            0
310     28.70      Millets        42          2            4
317     35.47      Tobacco        41          0            0
333     45.04       Barley        41          0            0

In [40]:
df.dtypes

Moisture       float64
Crop Type       object
Nitrogen         int64
Potassium        int64
Phosphorous      int64
dtype: object

In [39]:
# select phosphorous that were lie more than 38
df.query('Phosphorous>38')
# check out data types
df.dtypes

     Moisture    Crop Type  Nitrogen  Potassium  Phosphorous
43      37.32    Sugarcane        11          2           39
47      28.21       Pulses        13          3           42
57      28.93        Wheat        15          4           42
91      37.99      Tobacco        10          0           43
102     36.50    Oil seeds        19          0           39
110     38.68       Pulses         8          0           42
138     30.77       Cotton        18          4           39
142     49.05        Maize        13          4           39
143     45.23        Paddy        19          0           39
145     34.11        Paddy        15          0           43
148     42.11        Wheat         7          0           39
157     50.36    Sugarcane        10          0           43
171     54.87    Sugarcane         8          0           40
192     63.07       Pulses        13          1           40
206     30.10       Barley        12          1           45
210     44.81  Ground Nuts        16          0           40
215     32.84    Sugarcane        16          0           42
217     36.68        Paddy         7          2           41
230     54.54        Maize        10          0           40
237     23.88        Wheat        12          0           41
238     51.19        Paddy         9          1           39
255     39.00  Ground Nuts        17          0           39
263     20.00        Wheat        15          0           41
273     66.67      Tobacco        15          3           40
278     65.23       Barley        16          0           42
279     40.90    Sugarcane        10          2           41
290     61.14       Barley        13          0           41
297     40.93  Ground Nuts         9          0           42
329     39.73      Millets        13          4           42

In [45]:
# convert "crop type " to datatime type
df["Crop Type"] = df ["Crop Type"].astype('category')

In [46]:
df

     Moisture  Crop Type  Nitrogen  Potassium  Phosphorous
0       24.12     Cotton         8         19           16
1       25.17      Wheat        17          0           28
2       35.66     Barley        35          4            3
3       25.08      Maize        17          3           12
4       47.60     Cotton         9          9           34
..        ...        ...       ...        ...          ...
331     44.25  Oil seeds        10         14           10
332     49.34     Barley        35          0            0
333     45.04     Barley        41          0            0
334     36.03    Tobacco        10          3           30
335     62.27    Millets        11          2           33

[336 rows x 5 columns]

In [55]:
# query
df.query("`Crop Type` == 'Cotton'")

     Moisture Crop Type  Nitrogen  Potassium  Phosphorous
0       24.12    Cotton         8         19           16
4       47.60    Cotton         9          9           34
28      50.66    Cotton        10          6           25
61      32.87    Cotton         5          4           30
65      38.47    Cotton         6         13           17
68      69.57    Cotton        11          0           38
85      51.07    Cotton        13          0           12
105     26.52    Cotton         7          5           33
114     32.94    Cotton         8         12           14
121     35.24    Cotton        13          0           37
125     44.87    Cotton        37          1            0
129     32.98    Cotton        12          2            9
132     37.95    Cotton        15          4           15
138     30.77    Cotton        18          4           39
146     47.89    Cotton         8          0           12
172     44.72    Cotton        39          1            0
195     30.95    Cotton        12          4           15
198     32.84    Cotton        11          1           11
257     20.00    Cotton         9          9           25
274     57.32    Cotton        13          0           12
285     59.39    Cotton        13         16           10
287     41.64    Cotton        17          3           19
292     48.45    Cotton        37          0            0
312     44.02    Cotton        27          1           22
320     57.92    Cotton         2          4           27
326     37.02    Cotton        20          3           19

In [ ]:
# excercise: write the equivalent boolean slicing