In [37]:
import pandas as pd

In [38]:
# read csv file
df = pd.read_csv('soil_geotech_data.csv')

In [39]:
# show dataframe
df

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,29.96,55.46,24.12,Loamy,Cotton,8,19,16,Urea
1,36.83,69.28,25.17,Red,Wheat,17,0,28,28-28
2,26.95,60.64,35.66,Red,Barley,35,4,3,Urea
3,31.23,44.60,25.08,Red,Maize,17,3,12,DAP
4,33.78,51.39,47.60,Black,Cotton,9,9,34,28-28
...,...,...,...,...,...,...,...,...,...
331,35.30,59.61,44.25,Loamy,Oil seeds,10,14,10,Urea
332,39.39,71.67,49.34,Black,Barley,35,0,0,10-26-26
333,35.79,67.64,45.04,Red,Barley,41,0,0,Urea
334,37.78,73.38,36.03,Black,Tobacco,10,3,30,DAP
335,31.38,48.73,62.27,Loamy,Millets,11,2,33,28-28

# 1. Lambda function

In [40]:
# basic function
def sum_values(a,b):
    x= a+b
    return x

In [41]:
sum_values(2,3)

5

In [42]:
sum_values

In [43]:
# lambda function (one liner)
sum_values_lambda = lambda a,b:a+b

In [44]:
sum_values_lambda(2,4)

6

# 2. Apply + Lambda Function

In [45]:
# use lambda function to convert "Temperature in  degree Celscius " to degree Fahrenheit
df['Temparature'].apply(lambda x:1.8*x+32)

0       85.928
1       98.294
2       80.510
3       88.214
4       92.804
        ...
331     95.540
332    102.902
333     96.422
334    100.004
335     88.484
Name: Temparature, Length: 336, dtype: float64

In [46]:
# alternative
df['Temparature']*(1.8)+32

0       85.928
1       98.294
2       80.510
3       88.214
4       92.804
        ...
331     95.540
332    102.902
333     96.422
334    100.004
335     88.484
Name: Temparature, Length: 336, dtype: float64

In [47]:
# use lambda function to convert "Crop Type" series to upper case
df['Crop Type'].apply(lambda x:x.upper())

0         COTTON
1          WHEAT
2         BARLEY
3          MAIZE
4         COTTON
         ...
331    OIL SEEDS
332       BARLEY
333       BARLEY
334      TOBACCO
335      MILLETS
Name: Crop Type, Length: 336, dtype: object

In [48]:
# alternative with str attribute
df['Crop Type'].str.upper()

0         COTTON
1          WHEAT
2         BARLEY
3          MAIZE
4         COTTON
         ...
331    OIL SEEDS
332       BARLEY
333       BARLEY
334      TOBACCO
335      MILLETS
Name: Crop Type, Length: 336, dtype: object

In [49]:
df.dtypes

Temparature        float64
Humidity           float64
Moisture           float64
Soil Type           object
Crop Type           object
Nitrogen             int64
Potassium            int64
Phosphorous          int64
Fertilizer Name     object
dtype: object

In [52]:
df['Temp'] = df['Temparature'].astype('int64')
df.dtypes

Temparature          int64
Humidity           float64
Moisture           float64
Soil Type           object
Crop Type           object
Nitrogen             int64
Potassium            int64
Phosphorous          int64
Fertilizer Name     object
Temp                 int64
dtype: object

In [59]:
df['Temp'] = df['Temparature'].astype('datetime64[ns]')
df.dtypes

Temparature                 int64
Humidity                  float64
Moisture                  float64
Soil Type                  object
Crop Type                  object
Nitrogen                    int64
Potassium                   int64
Phosphorous                 int64
Fertilizer Name            object
Temp               datetime64[ns]
dtype: object

In [64]:
df['Temp'] = df['Temparature'].astype('int64')
# use lambda function to get the before decimal digit of the Moisture
df['Temp'].apply(lambda x:x)
# alternative with str attribute

0      29
1      36
2      26
3      31
4      33
       ..
331    35
332    39
333    35
334    37
335    31
Name: Temp, Length: 336, dtype: int64

In [68]:
def suggest_fertiliser(row):
    if row['Nitrogen'] > 30 and row['Phosphorous'] < 10:
        return 'urea'
    elif row['Phosphorous'] > 20 and row['Potassium'] < 10:
        return 'DAP'
    elif abs(row['Nitrogen'] - row['Phosphorous']) < 5:
        return '28-28'
    else:
        return '10-26-26'

df['suggested_fertiliser'] = df.apply(suggest_fertiliser, axis=1)

In [70]:
df

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name,Temp,suggested_fertiliser
0,29,55.46,24.12,Loamy,Cotton,8,19,16,Urea,29,10-26-26
1,36,69.28,25.17,Red,Wheat,17,0,28,28-28,36,DAP
2,26,60.64,35.66,Red,Barley,35,4,3,Urea,26,urea
3,31,44.60,25.08,Red,Maize,17,3,12,DAP,31,10-26-26
4,33,51.39,47.60,Black,Cotton,9,9,34,28-28,33,DAP
...,...,...,...,...,...,...,...,...,...,...,...
331,35,59.61,44.25,Loamy,Oil seeds,10,14,10,Urea,35,28-28
332,39,71.67,49.34,Black,Barley,35,0,0,10-26-26,39,urea
333,35,67.64,45.04,Red,Barley,41,0,0,Urea,35,urea
334,37,73.38,36.03,Black,Tobacco,10,3,30,DAP,37,DAP
335,31,48.73,62.27,Loamy,Millets,11,2,33,28-28,31,DAP

In [73]:
#apply lambda function to dataframe in order to calculate NPK
df.apply(lambda x:x['Nitrogen']+x['Potassium']+x['Phosphorous'], axis=1)

0      43
1      45
2      42
3      32
4      52
       ..
331    34
332    35
333    41
334    43
335    46
Length: 336, dtype: int64