In [1]:
import pandas as pd

In [3]:
# reading the csv file
df_exams = pd.read_csv('rainfall_by_districts_2019.csv')
df_exams

,S.No,District,Actual Rainfall in South West Monsoon (June'17 to September'17) in mm,Normal Rainfall in South West Monsoon (June'17 to September'17) in mm,Actual Rainfall in North East Monsoon (October'17 to December'17) in mm,Normal Rainfall in North East Monsoon (October'17 to December'17) in mm,Actual Rainfall in Winter Season (January'18 to and February'18) in mm,Normal Rainfall in Winter Season (January'18 to and February'18) in mm,Actual Rainfall in Hot Weather Season (March'18 to May'18) in mm,Normal Rainfall in Hot Weather Season (March'18 to May'18) in mm,Total Actual Rainfall (June'17 to May'18) in mm,Total Normal Rainfall (June'17 to May'18) in mm
0,1,Chennai,449.7,439.1,937.8,789.9,3.1,36.7,2.9,58.5,1393.5,1324.2
1,2,Kancheepuram,488.5,490.8,672.6,641.8,4.4,29.1,14.5,66.0,1180.0,1227.7
2,3,Tiruvallur,498.7,451.6,677.8,589.3,8.1,31.5,17.8,67.2,1202.4,1139.6
3,4,Cuddalore,465.7,383.1,775.9,697.8,55.0,44.1,14.4,81.7,1311.0,1206.7
4,5,Villupuram,441.3,408.3,535.7,499.1,10.5,28.2,24.2,76.0,1011.7,1011.6
5,6,Vellore,573.7,466.1,338.8,348.7,9.8,14.9,91.7,106.5,1014.0,936.2
6,7,Tiruvannamalai,621.9,468.1,524.9,446.5,34.9,26.5,52.4,98.9,1234.1,1040.0
7,8,Salem,484.7,440.6,341.9,370.5,15.4,16.0,179.2,170.8,1021.2,997.9
8,9,Namakkal,379.1,339.3,256.5,291.6,26.8,13.9,183.4,148.6,845.8,793.4
9,10,Dharmapuri,402.4,393.4,254.6,330.1,1.4,18.2,162.4,160.4,820.8,902.1
10,11,Krishnagiri,525.1,399.0,329.7,289.4,1.3,10.7,163.8,151.6,1019.9,850.7
11,12,Tiruppur,310.4,154.8,255.6,314.3,19.3,14.0,249.3,135.1,834.6,618.2
12,13,Coimbatore,510.0,189.8,182.6,328.9,12.8,20.3,311.8,150.3,1017.2,689.3
13,14,Erode,311.1,229.8,196.4,314.6,15.1,16.1,246.8,142.4,769.4,702.9
14,15,Tiruchirappalli,333.7,293.9,223.7,391.5,7.3,22.7,148.1,109.9,712.8,818.0
15,16,Karur,336.1,213.6,234.3,314.7,15.7,17.5,141.2,109.2,727.3,655.0
16,17,Perambalur,552.3,290.7,306.8,440.9,18.1,21.4,85.3,108.9,962.5,861.9
17,18,Pudukkottai,407.3,350.6,207.5,406.2,7.3,33.1,94.2,97.5,716.3,887.4
18,19,Thanjavur,479.5,318.4,433.7,550.3,21.9,42.3,59.4,102.1,994.5,1013.1
19,20,Tiruvarur,390.6,296.4,701.8,719.1,31.0,60.1,48.3,97.7,1171.7,1173.3
20,21,Nagapattinam,299.0,286.1,1132.3,941.0,78.8,85.7,19.7,80.5,1529.8,1393.3
21,22,Madurai,407.4,335.9,286.5,419.1,6.5,28.1,175.5,144.8,875.9,927.9
22,23,Theni,366.5,158.4,280.6,357.9,22.8,35.4,306.5,168.3,976.4,720.0
23,24,Dindigul,410.2,295.4,325.1,436.4,12.6,30.9,218.5,168.0,966.4,930.7
24,25,Ramanathapuram,211.3,149.3,259.1,491.7,2.2,51.3,110.8,115.5,583.4,807.8
25,26,Virudhunagar,293.6,196.8,332.3,419.0,28.5,42.8,238.0,161.5,892.4,820.1
26,27,Sivaganga,526.4,301.0,259.3,422.7,4.1,27.9,284.8,121.2,1074.6,872.8
27,28,Tirunelveli,212.6,142.4,665.5,467.2,25.8,69.3,247.8,166.2,1151.7,845.1
28,29,Thoothukudi,105.4,74.9,353.6,427.0,1.7,42.8,153.3,111.6,614.0,656.3
29,30,The Nilgiris,731.4,759.9,350.3,478.2,31.4,49.3,375.5,235.3,1488.6,1522.7
30,31,Ariyalur,549.4,392.0,491.7,545.5,25.8,32.5,52.2,101.8,1119.1,1071.8
31,32,Kanniyakumari,399.4,477.4,611.2,496.4,16.6,40.4,290.2,288.3,1317.4,1302.5
32,Average,State Average,421.1,330.8,429.3,468.0,18.0,32.9,148.9,128.2,1017.2,960.0

In [5]:
df_exams['average'] = (df_exams["Actual Rainfall in South West Monsoon (June'17 to September'17) in mm"]+	df_exams["Normal Rainfall in South West Monsoon (June'17 to September'17) in mm"]+	df_exams["Actual Rainfall in North East Monsoon (October'17 to December'17) in mm"])
df_exams

,S.No,District,Actual Rainfall in South West Monsoon (June'17 to September'17) in mm,Normal Rainfall in South West Monsoon (June'17 to September'17) in mm,Actual Rainfall in North East Monsoon (October'17 to December'17) in mm,Normal Rainfall in North East Monsoon (October'17 to December'17) in mm,Actual Rainfall in Winter Season (January'18 to and February'18) in mm,Normal Rainfall in Winter Season (January'18 to and February'18) in mm,Actual Rainfall in Hot Weather Season (March'18 to May'18) in mm,Normal Rainfall in Hot Weather Season (March'18 to May'18) in mm,Total Actual Rainfall (June'17 to May'18) in mm,Total Normal Rainfall (June'17 to May'18) in mm,average
0,1,Chennai,449.7,439.1,937.8,789.9,3.1,36.7,2.9,58.5,1393.5,1324.2,1826.6
1,2,Kancheepuram,488.5,490.8,672.6,641.8,4.4,29.1,14.5,66.0,1180.0,1227.7,1651.9
2,3,Tiruvallur,498.7,451.6,677.8,589.3,8.1,31.5,17.8,67.2,1202.4,1139.6,1628.1
3,4,Cuddalore,465.7,383.1,775.9,697.8,55.0,44.1,14.4,81.7,1311.0,1206.7,1624.7
4,5,Villupuram,441.3,408.3,535.7,499.1,10.5,28.2,24.2,76.0,1011.7,1011.6,1385.3
5,6,Vellore,573.7,466.1,338.8,348.7,9.8,14.9,91.7,106.5,1014.0,936.2,1378.6
6,7,Tiruvannamalai,621.9,468.1,524.9,446.5,34.9,26.5,52.4,98.9,1234.1,1040.0,1614.9
7,8,Salem,484.7,440.6,341.9,370.5,15.4,16.0,179.2,170.8,1021.2,997.9,1267.2
8,9,Namakkal,379.1,339.3,256.5,291.6,26.8,13.9,183.4,148.6,845.8,793.4,974.9
9,10,Dharmapuri,402.4,393.4,254.6,330.1,1.4,18.2,162.4,160.4,820.8,902.1,1050.4
10,11,Krishnagiri,525.1,399.0,329.7,289.4,1.3,10.7,163.8,151.6,1019.9,850.7,1253.8
11,12,Tiruppur,310.4,154.8,255.6,314.3,19.3,14.0,249.3,135.1,834.6,618.2,720.8
12,13,Coimbatore,510.0,189.8,182.6,328.9,12.8,20.3,311.8,150.3,1017.2,689.3,882.4
13,14,Erode,311.1,229.8,196.4,314.6,15.1,16.1,246.8,142.4,769.4,702.9,737.3
14,15,Tiruchirappalli,333.7,293.9,223.7,391.5,7.3,22.7,148.1,109.9,712.8,818.0,851.3
15,16,Karur,336.1,213.6,234.3,314.7,15.7,17.5,141.2,109.2,727.3,655.0,784.0
16,17,Perambalur,552.3,290.7,306.8,440.9,18.1,21.4,85.3,108.9,962.5,861.9,1149.8
17,18,Pudukkottai,407.3,350.6,207.5,406.2,7.3,33.1,94.2,97.5,716.3,887.4,965.4
18,19,Thanjavur,479.5,318.4,433.7,550.3,21.9,42.3,59.4,102.1,994.5,1013.1,1231.6
19,20,Tiruvarur,390.6,296.4,701.8,719.1,31.0,60.1,48.3,97.7,1171.7,1173.3,1388.8
20,21,Nagapattinam,299.0,286.1,1132.3,941.0,78.8,85.7,19.7,80.5,1529.8,1393.3,1717.4
21,22,Madurai,407.4,335.9,286.5,419.1,6.5,28.1,175.5,144.8,875.9,927.9,1029.8
22,23,Theni,366.5,158.4,280.6,357.9,22.8,35.4,306.5,168.3,976.4,720.0,805.5
23,24,Dindigul,410.2,295.4,325.1,436.4,12.6,30.9,218.5,168.0,966.4,930.7,1030.7
24,25,Ramanathapuram,211.3,149.3,259.1,491.7,2.2,51.3,110.8,115.5,583.4,807.8,619.7
25,26,Virudhunagar,293.6,196.8,332.3,419.0,28.5,42.8,238.0,161.5,892.4,820.1,822.7
26,27,Sivaganga,526.4,301.0,259.3,422.7,4.1,27.9,284.8,121.2,1074.6,872.8,1086.7
27,28,Tirunelveli,212.6,142.4,665.5,467.2,25.8,69.3,247.8,166.2,1151.7,845.1,1020.5
28,29,Thoothukudi,105.4,74.9,353.6,427.0,1.7,42.8,153.3,111.6,614.0,656.3,533.9
29,30,The Nilgiris,731.4,759.9,350.3,478.2,31.4,49.3,375.5,235.3,1488.6,1522.7,1841.6
30,31,Ariyalur,549.4,392.0,491.7,545.5,25.8,32.5,52.2,101.8,1119.1,1071.8,1433.1
31,32,Kanniyakumari,399.4,477.4,611.2,496.4,16.6,40.4,290.2,288.3,1317.4,1302.5,1488.0
32,Average,State Average,421.1,330.8,429.3,468.0,18.0,32.9,148.9,128.2,1017.2,960.0,1181.2

# 1 sort a dataframe

In [7]:
# sort by one column
df_exams.sort_values('average')

,S.No,District,Actual Rainfall in South West Monsoon (June'17 to September'17) in mm,Normal Rainfall in South West Monsoon (June'17 to September'17) in mm,Actual Rainfall in North East Monsoon (October'17 to December'17) in mm,Normal Rainfall in North East Monsoon (October'17 to December'17) in mm,Actual Rainfall in Winter Season (January'18 to and February'18) in mm,Normal Rainfall in Winter Season (January'18 to and February'18) in mm,Actual Rainfall in Hot Weather Season (March'18 to May'18) in mm,Normal Rainfall in Hot Weather Season (March'18 to May'18) in mm,Total Actual Rainfall (June'17 to May'18) in mm,Total Normal Rainfall (June'17 to May'18) in mm,average
28,29,Thoothukudi,105.4,74.9,353.6,427.0,1.7,42.8,153.3,111.6,614.0,656.3,533.9
24,25,Ramanathapuram,211.3,149.3,259.1,491.7,2.2,51.3,110.8,115.5,583.4,807.8,619.7
11,12,Tiruppur,310.4,154.8,255.6,314.3,19.3,14.0,249.3,135.1,834.6,618.2,720.8
13,14,Erode,311.1,229.8,196.4,314.6,15.1,16.1,246.8,142.4,769.4,702.9,737.3
15,16,Karur,336.1,213.6,234.3,314.7,15.7,17.5,141.2,109.2,727.3,655.0,784.0
22,23,Theni,366.5,158.4,280.6,357.9,22.8,35.4,306.5,168.3,976.4,720.0,805.5
25,26,Virudhunagar,293.6,196.8,332.3,419.0,28.5,42.8,238.0,161.5,892.4,820.1,822.7
14,15,Tiruchirappalli,333.7,293.9,223.7,391.5,7.3,22.7,148.1,109.9,712.8,818.0,851.3
12,13,Coimbatore,510.0,189.8,182.6,328.9,12.8,20.3,311.8,150.3,1017.2,689.3,882.4
17,18,Pudukkottai,407.3,350.6,207.5,406.2,7.3,33.1,94.2,97.5,716.3,887.4,965.4
8,9,Namakkal,379.1,339.3,256.5,291.6,26.8,13.9,183.4,148.6,845.8,793.4,974.9
27,28,Tirunelveli,212.6,142.4,665.5,467.2,25.8,69.3,247.8,166.2,1151.7,845.1,1020.5
21,22,Madurai,407.4,335.9,286.5,419.1,6.5,28.1,175.5,144.8,875.9,927.9,1029.8
23,24,Dindigul,410.2,295.4,325.1,436.4,12.6,30.9,218.5,168.0,966.4,930.7,1030.7
9,10,Dharmapuri,402.4,393.4,254.6,330.1,1.4,18.2,162.4,160.4,820.8,902.1,1050.4
26,27,Sivaganga,526.4,301.0,259.3,422.7,4.1,27.9,284.8,121.2,1074.6,872.8,1086.7
16,17,Perambalur,552.3,290.7,306.8,440.9,18.1,21.4,85.3,108.9,962.5,861.9,1149.8
32,Average,State Average,421.1,330.8,429.3,468.0,18.0,32.9,148.9,128.2,1017.2,960.0,1181.2
18,19,Thanjavur,479.5,318.4,433.7,550.3,21.9,42.3,59.4,102.1,994.5,1013.1,1231.6
10,11,Krishnagiri,525.1,399.0,329.7,289.4,1.3,10.7,163.8,151.6,1019.9,850.7,1253.8
7,8,Salem,484.7,440.6,341.9,370.5,15.4,16.0,179.2,170.8,1021.2,997.9,1267.2
5,6,Vellore,573.7,466.1,338.8,348.7,9.8,14.9,91.7,106.5,1014.0,936.2,1378.6
4,5,Villupuram,441.3,408.3,535.7,499.1,10.5,28.2,24.2,76.0,1011.7,1011.6,1385.3
19,20,Tiruvarur,390.6,296.4,701.8,719.1,31.0,60.1,48.3,97.7,1171.7,1173.3,1388.8
30,31,Ariyalur,549.4,392.0,491.7,545.5,25.8,32.5,52.2,101.8,1119.1,1071.8,1433.1
31,32,Kanniyakumari,399.4,477.4,611.2,496.4,16.6,40.4,290.2,288.3,1317.4,1302.5,1488.0
6,7,Tiruvannamalai,621.9,468.1,524.9,446.5,34.9,26.5,52.4,98.9,1234.1,1040.0,1614.9
3,4,Cuddalore,465.7,383.1,775.9,697.8,55.0,44.1,14.4,81.7,1311.0,1206.7,1624.7
2,3,Tiruvallur,498.7,451.6,677.8,589.3,8.1,31.5,17.8,67.2,1202.4,1139.6,1628.1
1,2,Kancheepuram,488.5,490.8,672.6,641.8,4.4,29.1,14.5,66.0,1180.0,1227.7,1651.9
20,21,Nagapattinam,299.0,286.1,1132.3,941.0,78.8,85.7,19.7,80.5,1529.8,1393.3,1717.4
0,1,Chennai,449.7,439.1,937.8,789.9,3.1,36.7,2.9,58.5,1393.5,1324.2,1826.6
29,30,The Nilgiris,731.4,759.9,350.3,478.2,31.4,49.3,375.5,235.3,1488.6,1522.7,1841.6

In [8]:
# sort descending by one column
df_exams.sort_values('average', ascending=False)

,S.No,District,Actual Rainfall in South West Monsoon (June'17 to September'17) in mm,Normal Rainfall in South West Monsoon (June'17 to September'17) in mm,Actual Rainfall in North East Monsoon (October'17 to December'17) in mm,Normal Rainfall in North East Monsoon (October'17 to December'17) in mm,Actual Rainfall in Winter Season (January'18 to and February'18) in mm,Normal Rainfall in Winter Season (January'18 to and February'18) in mm,Actual Rainfall in Hot Weather Season (March'18 to May'18) in mm,Normal Rainfall in Hot Weather Season (March'18 to May'18) in mm,Total Actual Rainfall (June'17 to May'18) in mm,Total Normal Rainfall (June'17 to May'18) in mm,average
29,30,The Nilgiris,731.4,759.9,350.3,478.2,31.4,49.3,375.5,235.3,1488.6,1522.7,1841.6
0,1,Chennai,449.7,439.1,937.8,789.9,3.1,36.7,2.9,58.5,1393.5,1324.2,1826.6
20,21,Nagapattinam,299.0,286.1,1132.3,941.0,78.8,85.7,19.7,80.5,1529.8,1393.3,1717.4
1,2,Kancheepuram,488.5,490.8,672.6,641.8,4.4,29.1,14.5,66.0,1180.0,1227.7,1651.9
2,3,Tiruvallur,498.7,451.6,677.8,589.3,8.1,31.5,17.8,67.2,1202.4,1139.6,1628.1
3,4,Cuddalore,465.7,383.1,775.9,697.8,55.0,44.1,14.4,81.7,1311.0,1206.7,1624.7
6,7,Tiruvannamalai,621.9,468.1,524.9,446.5,34.9,26.5,52.4,98.9,1234.1,1040.0,1614.9
31,32,Kanniyakumari,399.4,477.4,611.2,496.4,16.6,40.4,290.2,288.3,1317.4,1302.5,1488.0
30,31,Ariyalur,549.4,392.0,491.7,545.5,25.8,32.5,52.2,101.8,1119.1,1071.8,1433.1
19,20,Tiruvarur,390.6,296.4,701.8,719.1,31.0,60.1,48.3,97.7,1171.7,1173.3,1388.8
4,5,Villupuram,441.3,408.3,535.7,499.1,10.5,28.2,24.2,76.0,1011.7,1011.6,1385.3
5,6,Vellore,573.7,466.1,338.8,348.7,9.8,14.9,91.7,106.5,1014.0,936.2,1378.6
7,8,Salem,484.7,440.6,341.9,370.5,15.4,16.0,179.2,170.8,1021.2,997.9,1267.2
10,11,Krishnagiri,525.1,399.0,329.7,289.4,1.3,10.7,163.8,151.6,1019.9,850.7,1253.8
18,19,Thanjavur,479.5,318.4,433.7,550.3,21.9,42.3,59.4,102.1,994.5,1013.1,1231.6
32,Average,State Average,421.1,330.8,429.3,468.0,18.0,32.9,148.9,128.2,1017.2,960.0,1181.2
16,17,Perambalur,552.3,290.7,306.8,440.9,18.1,21.4,85.3,108.9,962.5,861.9,1149.8
26,27,Sivaganga,526.4,301.0,259.3,422.7,4.1,27.9,284.8,121.2,1074.6,872.8,1086.7
9,10,Dharmapuri,402.4,393.4,254.6,330.1,1.4,18.2,162.4,160.4,820.8,902.1,1050.4
23,24,Dindigul,410.2,295.4,325.1,436.4,12.6,30.9,218.5,168.0,966.4,930.7,1030.7
21,22,Madurai,407.4,335.9,286.5,419.1,6.5,28.1,175.5,144.8,875.9,927.9,1029.8
27,28,Tirunelveli,212.6,142.4,665.5,467.2,25.8,69.3,247.8,166.2,1151.7,845.1,1020.5
8,9,Namakkal,379.1,339.3,256.5,291.6,26.8,13.9,183.4,148.6,845.8,793.4,974.9
17,18,Pudukkottai,407.3,350.6,207.5,406.2,7.3,33.1,94.2,97.5,716.3,887.4,965.4
12,13,Coimbatore,510.0,189.8,182.6,328.9,12.8,20.3,311.8,150.3,1017.2,689.3,882.4
14,15,Tiruchirappalli,333.7,293.9,223.7,391.5,7.3,22.7,148.1,109.9,712.8,818.0,851.3
25,26,Virudhunagar,293.6,196.8,332.3,419.0,28.5,42.8,238.0,161.5,892.4,820.1,822.7
22,23,Theni,366.5,158.4,280.6,357.9,22.8,35.4,306.5,168.3,976.4,720.0,805.5
15,16,Karur,336.1,213.6,234.3,314.7,15.7,17.5,141.2,109.2,727.3,655.0,784.0
13,14,Erode,311.1,229.8,196.4,314.6,15.1,16.1,246.8,142.4,769.4,702.9,737.3
11,12,Tiruppur,310.4,154.8,255.6,314.3,19.3,14.0,249.3,135.1,834.6,618.2,720.8
24,25,Ramanathapuram,211.3,149.3,259.1,491.7,2.2,51.3,110.8,115.5,583.4,807.8,619.7
28,29,Thoothukudi,105.4,74.9,353.6,427.0,1.7,42.8,153.3,111.6,614.0,656.3,533.9

In [9]:
# sort descending by multiple columns
df_exams.sort_values(['average', "Total Normal Rainfall (June'17 to May'18) in mm"], ascending=False)

,S.No,District,Actual Rainfall in South West Monsoon (June'17 to September'17) in mm,Normal Rainfall in South West Monsoon (June'17 to September'17) in mm,Actual Rainfall in North East Monsoon (October'17 to December'17) in mm,Normal Rainfall in North East Monsoon (October'17 to December'17) in mm,Actual Rainfall in Winter Season (January'18 to and February'18) in mm,Normal Rainfall in Winter Season (January'18 to and February'18) in mm,Actual Rainfall in Hot Weather Season (March'18 to May'18) in mm,Normal Rainfall in Hot Weather Season (March'18 to May'18) in mm,Total Actual Rainfall (June'17 to May'18) in mm,Total Normal Rainfall (June'17 to May'18) in mm,average
29,30,The Nilgiris,731.4,759.9,350.3,478.2,31.4,49.3,375.5,235.3,1488.6,1522.7,1841.6
0,1,Chennai,449.7,439.1,937.8,789.9,3.1,36.7,2.9,58.5,1393.5,1324.2,1826.6
20,21,Nagapattinam,299.0,286.1,1132.3,941.0,78.8,85.7,19.7,80.5,1529.8,1393.3,1717.4
1,2,Kancheepuram,488.5,490.8,672.6,641.8,4.4,29.1,14.5,66.0,1180.0,1227.7,1651.9
2,3,Tiruvallur,498.7,451.6,677.8,589.3,8.1,31.5,17.8,67.2,1202.4,1139.6,1628.1
3,4,Cuddalore,465.7,383.1,775.9,697.8,55.0,44.1,14.4,81.7,1311.0,1206.7,1624.7
6,7,Tiruvannamalai,621.9,468.1,524.9,446.5,34.9,26.5,52.4,98.9,1234.1,1040.0,1614.9
31,32,Kanniyakumari,399.4,477.4,611.2,496.4,16.6,40.4,290.2,288.3,1317.4,1302.5,1488.0
30,31,Ariyalur,549.4,392.0,491.7,545.5,25.8,32.5,52.2,101.8,1119.1,1071.8,1433.1
19,20,Tiruvarur,390.6,296.4,701.8,719.1,31.0,60.1,48.3,97.7,1171.7,1173.3,1388.8
4,5,Villupuram,441.3,408.3,535.7,499.1,10.5,28.2,24.2,76.0,1011.7,1011.6,1385.3
5,6,Vellore,573.7,466.1,338.8,348.7,9.8,14.9,91.7,106.5,1014.0,936.2,1378.6
7,8,Salem,484.7,440.6,341.9,370.5,15.4,16.0,179.2,170.8,1021.2,997.9,1267.2
10,11,Krishnagiri,525.1,399.0,329.7,289.4,1.3,10.7,163.8,151.6,1019.9,850.7,1253.8
18,19,Thanjavur,479.5,318.4,433.7,550.3,21.9,42.3,59.4,102.1,994.5,1013.1,1231.6
32,Average,State Average,421.1,330.8,429.3,468.0,18.0,32.9,148.9,128.2,1017.2,960.0,1181.2
16,17,Perambalur,552.3,290.7,306.8,440.9,18.1,21.4,85.3,108.9,962.5,861.9,1149.8
26,27,Sivaganga,526.4,301.0,259.3,422.7,4.1,27.9,284.8,121.2,1074.6,872.8,1086.7
9,10,Dharmapuri,402.4,393.4,254.6,330.1,1.4,18.2,162.4,160.4,820.8,902.1,1050.4
23,24,Dindigul,410.2,295.4,325.1,436.4,12.6,30.9,218.5,168.0,966.4,930.7,1030.7
21,22,Madurai,407.4,335.9,286.5,419.1,6.5,28.1,175.5,144.8,875.9,927.9,1029.8
27,28,Tirunelveli,212.6,142.4,665.5,467.2,25.8,69.3,247.8,166.2,1151.7,845.1,1020.5
8,9,Namakkal,379.1,339.3,256.5,291.6,26.8,13.9,183.4,148.6,845.8,793.4,974.9
17,18,Pudukkottai,407.3,350.6,207.5,406.2,7.3,33.1,94.2,97.5,716.3,887.4,965.4
12,13,Coimbatore,510.0,189.8,182.6,328.9,12.8,20.3,311.8,150.3,1017.2,689.3,882.4
14,15,Tiruchirappalli,333.7,293.9,223.7,391.5,7.3,22.7,148.1,109.9,712.8,818.0,851.3
25,26,Virudhunagar,293.6,196.8,332.3,419.0,28.5,42.8,238.0,161.5,892.4,820.1,822.7
22,23,Theni,366.5,158.4,280.6,357.9,22.8,35.4,306.5,168.3,976.4,720.0,805.5
15,16,Karur,336.1,213.6,234.3,314.7,15.7,17.5,141.2,109.2,727.3,655.0,784.0
13,14,Erode,311.1,229.8,196.4,314.6,15.1,16.1,246.8,142.4,769.4,702.9,737.3
11,12,Tiruppur,310.4,154.8,255.6,314.3,19.3,14.0,249.3,135.1,834.6,618.2,720.8
24,25,Ramanathapuram,211.3,149.3,259.1,491.7,2.2,51.3,110.8,115.5,583.4,807.8,619.7
28,29,Thoothukudi,105.4,74.9,353.6,427.0,1.7,42.8,153.3,111.6,614.0,656.3,533.9

In [13]:
# sort descending by multiple columns average as first priority and Total Normal Rainfall (June'17 to May'18) in mm as second priority
df_exams.sort_values(['average', "Total Normal Rainfall (June'17 to May'18) in mm"], ascending=False)

,S.No,District,Actual Rainfall in South West Monsoon (June'17 to September'17) in mm,Normal Rainfall in South West Monsoon (June'17 to September'17) in mm,Actual Rainfall in North East Monsoon (October'17 to December'17) in mm,Normal Rainfall in North East Monsoon (October'17 to December'17) in mm,Actual Rainfall in Winter Season (January'18 to and February'18) in mm,Normal Rainfall in Winter Season (January'18 to and February'18) in mm,Actual Rainfall in Hot Weather Season (March'18 to May'18) in mm,Normal Rainfall in Hot Weather Season (March'18 to May'18) in mm,Total Actual Rainfall (June'17 to May'18) in mm,Total Normal Rainfall (June'17 to May'18) in mm,average
29,30,The Nilgiris,731.4,759.9,350.3,478.2,31.4,49.3,375.5,235.3,1488.6,1522.7,1841.6
0,1,Chennai,449.7,439.1,937.8,789.9,3.1,36.7,2.9,58.5,1393.5,1324.2,1826.6
20,21,Nagapattinam,299.0,286.1,1132.3,941.0,78.8,85.7,19.7,80.5,1529.8,1393.3,1717.4
1,2,Kancheepuram,488.5,490.8,672.6,641.8,4.4,29.1,14.5,66.0,1180.0,1227.7,1651.9
2,3,Tiruvallur,498.7,451.6,677.8,589.3,8.1,31.5,17.8,67.2,1202.4,1139.6,1628.1
3,4,Cuddalore,465.7,383.1,775.9,697.8,55.0,44.1,14.4,81.7,1311.0,1206.7,1624.7
6,7,Tiruvannamalai,621.9,468.1,524.9,446.5,34.9,26.5,52.4,98.9,1234.1,1040.0,1614.9
31,32,Kanniyakumari,399.4,477.4,611.2,496.4,16.6,40.4,290.2,288.3,1317.4,1302.5,1488.0
30,31,Ariyalur,549.4,392.0,491.7,545.5,25.8,32.5,52.2,101.8,1119.1,1071.8,1433.1
19,20,Tiruvarur,390.6,296.4,701.8,719.1,31.0,60.1,48.3,97.7,1171.7,1173.3,1388.8
4,5,Villupuram,441.3,408.3,535.7,499.1,10.5,28.2,24.2,76.0,1011.7,1011.6,1385.3
5,6,Vellore,573.7,466.1,338.8,348.7,9.8,14.9,91.7,106.5,1014.0,936.2,1378.6
7,8,Salem,484.7,440.6,341.9,370.5,15.4,16.0,179.2,170.8,1021.2,997.9,1267.2
10,11,Krishnagiri,525.1,399.0,329.7,289.4,1.3,10.7,163.8,151.6,1019.9,850.7,1253.8
18,19,Thanjavur,479.5,318.4,433.7,550.3,21.9,42.3,59.4,102.1,994.5,1013.1,1231.6
32,Average,State Average,421.1,330.8,429.3,468.0,18.0,32.9,148.9,128.2,1017.2,960.0,1181.2
16,17,Perambalur,552.3,290.7,306.8,440.9,18.1,21.4,85.3,108.9,962.5,861.9,1149.8
26,27,Sivaganga,526.4,301.0,259.3,422.7,4.1,27.9,284.8,121.2,1074.6,872.8,1086.7
9,10,Dharmapuri,402.4,393.4,254.6,330.1,1.4,18.2,162.4,160.4,820.8,902.1,1050.4
23,24,Dindigul,410.2,295.4,325.1,436.4,12.6,30.9,218.5,168.0,966.4,930.7,1030.7
21,22,Madurai,407.4,335.9,286.5,419.1,6.5,28.1,175.5,144.8,875.9,927.9,1029.8
27,28,Tirunelveli,212.6,142.4,665.5,467.2,25.8,69.3,247.8,166.2,1151.7,845.1,1020.5
8,9,Namakkal,379.1,339.3,256.5,291.6,26.8,13.9,183.4,148.6,845.8,793.4,974.9
17,18,Pudukkottai,407.3,350.6,207.5,406.2,7.3,33.1,94.2,97.5,716.3,887.4,965.4
12,13,Coimbatore,510.0,189.8,182.6,328.9,12.8,20.3,311.8,150.3,1017.2,689.3,882.4
14,15,Tiruchirappalli,333.7,293.9,223.7,391.5,7.3,22.7,148.1,109.9,712.8,818.0,851.3
25,26,Virudhunagar,293.6,196.8,332.3,419.0,28.5,42.8,238.0,161.5,892.4,820.1,822.7
22,23,Theni,366.5,158.4,280.6,357.9,22.8,35.4,306.5,168.3,976.4,720.0,805.5
15,16,Karur,336.1,213.6,234.3,314.7,15.7,17.5,141.2,109.2,727.3,655.0,784.0
13,14,Erode,311.1,229.8,196.4,314.6,15.1,16.1,246.8,142.4,769.4,702.9,737.3
11,12,Tiruppur,310.4,154.8,255.6,314.3,19.3,14.0,249.3,135.1,834.6,618.2,720.8
24,25,Ramanathapuram,211.3,149.3,259.1,491.7,2.2,51.3,110.8,115.5,583.4,807.8,619.7
28,29,Thoothukudi,105.4,74.9,353.6,427.0,1.7,42.8,153.3,111.6,614.0,656.3,533.9

In [15]:
# sort descending by multiple columns and update dataframe
df_exams.sort_values(['average', "Total Normal Rainfall (June'17 to May'18) in mm"], ascending=False,
                    inplace=True)

In [16]:
df_exams

,S.No,District,Actual Rainfall in South West Monsoon (June'17 to September'17) in mm,Normal Rainfall in South West Monsoon (June'17 to September'17) in mm,Actual Rainfall in North East Monsoon (October'17 to December'17) in mm,Normal Rainfall in North East Monsoon (October'17 to December'17) in mm,Actual Rainfall in Winter Season (January'18 to and February'18) in mm,Normal Rainfall in Winter Season (January'18 to and February'18) in mm,Actual Rainfall in Hot Weather Season (March'18 to May'18) in mm,Normal Rainfall in Hot Weather Season (March'18 to May'18) in mm,Total Actual Rainfall (June'17 to May'18) in mm,Total Normal Rainfall (June'17 to May'18) in mm,average
29,30,The Nilgiris,731.4,759.9,350.3,478.2,31.4,49.3,375.5,235.3,1488.6,1522.7,1841.6
0,1,Chennai,449.7,439.1,937.8,789.9,3.1,36.7,2.9,58.5,1393.5,1324.2,1826.6
20,21,Nagapattinam,299.0,286.1,1132.3,941.0,78.8,85.7,19.7,80.5,1529.8,1393.3,1717.4
1,2,Kancheepuram,488.5,490.8,672.6,641.8,4.4,29.1,14.5,66.0,1180.0,1227.7,1651.9
2,3,Tiruvallur,498.7,451.6,677.8,589.3,8.1,31.5,17.8,67.2,1202.4,1139.6,1628.1
3,4,Cuddalore,465.7,383.1,775.9,697.8,55.0,44.1,14.4,81.7,1311.0,1206.7,1624.7
6,7,Tiruvannamalai,621.9,468.1,524.9,446.5,34.9,26.5,52.4,98.9,1234.1,1040.0,1614.9
31,32,Kanniyakumari,399.4,477.4,611.2,496.4,16.6,40.4,290.2,288.3,1317.4,1302.5,1488.0
30,31,Ariyalur,549.4,392.0,491.7,545.5,25.8,32.5,52.2,101.8,1119.1,1071.8,1433.1
19,20,Tiruvarur,390.6,296.4,701.8,719.1,31.0,60.1,48.3,97.7,1171.7,1173.3,1388.8
4,5,Villupuram,441.3,408.3,535.7,499.1,10.5,28.2,24.2,76.0,1011.7,1011.6,1385.3
5,6,Vellore,573.7,466.1,338.8,348.7,9.8,14.9,91.7,106.5,1014.0,936.2,1378.6
7,8,Salem,484.7,440.6,341.9,370.5,15.4,16.0,179.2,170.8,1021.2,997.9,1267.2
10,11,Krishnagiri,525.1,399.0,329.7,289.4,1.3,10.7,163.8,151.6,1019.9,850.7,1253.8
18,19,Thanjavur,479.5,318.4,433.7,550.3,21.9,42.3,59.4,102.1,994.5,1013.1,1231.6
32,Average,State Average,421.1,330.8,429.3,468.0,18.0,32.9,148.9,128.2,1017.2,960.0,1181.2
16,17,Perambalur,552.3,290.7,306.8,440.9,18.1,21.4,85.3,108.9,962.5,861.9,1149.8
26,27,Sivaganga,526.4,301.0,259.3,422.7,4.1,27.9,284.8,121.2,1074.6,872.8,1086.7
9,10,Dharmapuri,402.4,393.4,254.6,330.1,1.4,18.2,162.4,160.4,820.8,902.1,1050.4
23,24,Dindigul,410.2,295.4,325.1,436.4,12.6,30.9,218.5,168.0,966.4,930.7,1030.7
21,22,Madurai,407.4,335.9,286.5,419.1,6.5,28.1,175.5,144.8,875.9,927.9,1029.8
27,28,Tirunelveli,212.6,142.4,665.5,467.2,25.8,69.3,247.8,166.2,1151.7,845.1,1020.5
8,9,Namakkal,379.1,339.3,256.5,291.6,26.8,13.9,183.4,148.6,845.8,793.4,974.9
17,18,Pudukkottai,407.3,350.6,207.5,406.2,7.3,33.1,94.2,97.5,716.3,887.4,965.4
12,13,Coimbatore,510.0,189.8,182.6,328.9,12.8,20.3,311.8,150.3,1017.2,689.3,882.4
14,15,Tiruchirappalli,333.7,293.9,223.7,391.5,7.3,22.7,148.1,109.9,712.8,818.0,851.3
25,26,Virudhunagar,293.6,196.8,332.3,419.0,28.5,42.8,238.0,161.5,892.4,820.1,822.7
22,23,Theni,366.5,158.4,280.6,357.9,22.8,35.4,306.5,168.3,976.4,720.0,805.5
15,16,Karur,336.1,213.6,234.3,314.7,15.7,17.5,141.2,109.2,727.3,655.0,784.0
13,14,Erode,311.1,229.8,196.4,314.6,15.1,16.1,246.8,142.4,769.4,702.9,737.3
11,12,Tiruppur,310.4,154.8,255.6,314.3,19.3,14.0,249.3,135.1,834.6,618.2,720.8
24,25,Ramanathapuram,211.3,149.3,259.1,491.7,2.2,51.3,110.8,115.5,583.4,807.8,619.7
28,29,Thoothukudi,105.4,74.9,353.6,427.0,1.7,42.8,153.3,111.6,614.0,656.3,533.9

In [19]:
# sort descending with a key function
df_exams.sort_values('District', ascending=False,
                    key=lambda col:col.str.lower())

,S.No,District,Actual Rainfall in South West Monsoon (June'17 to September'17) in mm,Normal Rainfall in South West Monsoon (June'17 to September'17) in mm,Actual Rainfall in North East Monsoon (October'17 to December'17) in mm,Normal Rainfall in North East Monsoon (October'17 to December'17) in mm,Actual Rainfall in Winter Season (January'18 to and February'18) in mm,Normal Rainfall in Winter Season (January'18 to and February'18) in mm,Actual Rainfall in Hot Weather Season (March'18 to May'18) in mm,Normal Rainfall in Hot Weather Season (March'18 to May'18) in mm,Total Actual Rainfall (June'17 to May'18) in mm,Total Normal Rainfall (June'17 to May'18) in mm,average
25,26,Virudhunagar,293.6,196.8,332.3,419.0,28.5,42.8,238.0,161.5,892.4,820.1,822.7
4,5,Villupuram,441.3,408.3,535.7,499.1,10.5,28.2,24.2,76.0,1011.7,1011.6,1385.3
5,6,Vellore,573.7,466.1,338.8,348.7,9.8,14.9,91.7,106.5,1014.0,936.2,1378.6
19,20,Tiruvarur,390.6,296.4,701.8,719.1,31.0,60.1,48.3,97.7,1171.7,1173.3,1388.8
6,7,Tiruvannamalai,621.9,468.1,524.9,446.5,34.9,26.5,52.4,98.9,1234.1,1040.0,1614.9
2,3,Tiruvallur,498.7,451.6,677.8,589.3,8.1,31.5,17.8,67.2,1202.4,1139.6,1628.1
11,12,Tiruppur,310.4,154.8,255.6,314.3,19.3,14.0,249.3,135.1,834.6,618.2,720.8
27,28,Tirunelveli,212.6,142.4,665.5,467.2,25.8,69.3,247.8,166.2,1151.7,845.1,1020.5
14,15,Tiruchirappalli,333.7,293.9,223.7,391.5,7.3,22.7,148.1,109.9,712.8,818.0,851.3
28,29,Thoothukudi,105.4,74.9,353.6,427.0,1.7,42.8,153.3,111.6,614.0,656.3,533.9
22,23,Theni,366.5,158.4,280.6,357.9,22.8,35.4,306.5,168.3,976.4,720.0,805.5
29,30,The Nilgiris,731.4,759.9,350.3,478.2,31.4,49.3,375.5,235.3,1488.6,1522.7,1841.6
18,19,Thanjavur,479.5,318.4,433.7,550.3,21.9,42.3,59.4,102.1,994.5,1013.1,1231.6
32,Average,State Average,421.1,330.8,429.3,468.0,18.0,32.9,148.9,128.2,1017.2,960.0,1181.2
26,27,Sivaganga,526.4,301.0,259.3,422.7,4.1,27.9,284.8,121.2,1074.6,872.8,1086.7
7,8,Salem,484.7,440.6,341.9,370.5,15.4,16.0,179.2,170.8,1021.2,997.9,1267.2
24,25,Ramanathapuram,211.3,149.3,259.1,491.7,2.2,51.3,110.8,115.5,583.4,807.8,619.7
17,18,Pudukkottai,407.3,350.6,207.5,406.2,7.3,33.1,94.2,97.5,716.3,887.4,965.4
16,17,Perambalur,552.3,290.7,306.8,440.9,18.1,21.4,85.3,108.9,962.5,861.9,1149.8
8,9,Namakkal,379.1,339.3,256.5,291.6,26.8,13.9,183.4,148.6,845.8,793.4,974.9
20,21,Nagapattinam,299.0,286.1,1132.3,941.0,78.8,85.7,19.7,80.5,1529.8,1393.3,1717.4
21,22,Madurai,407.4,335.9,286.5,419.1,6.5,28.1,175.5,144.8,875.9,927.9,1029.8
10,11,Krishnagiri,525.1,399.0,329.7,289.4,1.3,10.7,163.8,151.6,1019.9,850.7,1253.8
15,16,Karur,336.1,213.6,234.3,314.7,15.7,17.5,141.2,109.2,727.3,655.0,784.0
31,32,Kanniyakumari,399.4,477.4,611.2,496.4,16.6,40.4,290.2,288.3,1317.4,1302.5,1488.0
1,2,Kancheepuram,488.5,490.8,672.6,641.8,4.4,29.1,14.5,66.0,1180.0,1227.7,1651.9
13,14,Erode,311.1,229.8,196.4,314.6,15.1,16.1,246.8,142.4,769.4,702.9,737.3
23,24,Dindigul,410.2,295.4,325.1,436.4,12.6,30.9,218.5,168.0,966.4,930.7,1030.7
9,10,Dharmapuri,402.4,393.4,254.6,330.1,1.4,18.2,162.4,160.4,820.8,902.1,1050.4
3,4,Cuddalore,465.7,383.1,775.9,697.8,55.0,44.1,14.4,81.7,1311.0,1206.7,1624.7
12,13,Coimbatore,510.0,189.8,182.6,328.9,12.8,20.3,311.8,150.3,1017.2,689.3,882.4
0,1,Chennai,449.7,439.1,937.8,789.9,3.1,36.7,2.9,58.5,1393.5,1324.2,1826.6
30,31,Ariyalur,549.4,392.0,491.7,545.5,25.8,32.5,52.2,101.8,1119.1,1071.8,1433.1